package com.semioe.api.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ApiMotherhoodUser implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	private String liveTime;
	private Integer husbandCardType;

	public Integer getHusbandCardType() {
		return husbandCardType;
	}

	public void setHusbandCardType(Integer husbandCardType) {
		this.husbandCardType = husbandCardType;
	}

	public String getLiveTime() {
		return liveTime;
	}

	public void setLiveTime(String liveTime) {
		this.liveTime = liveTime;
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.created_date
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	private Date createdDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.document_type
	 *
	 * @mbg.generated
	 */
	private Integer documentType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.document_code
	 *
	 * @mbg.generated
	 */
	private String documentCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.name
	 *
	 * @mbg.generated
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.birthday
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	private Date birthday;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.age
	 *
	 * @mbg.generated
	 */
	private Integer age;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.cultural_status
	 *
	 * @mbg.generated
	 */
	private Integer culturalStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.nationality
	 *
	 * @mbg.generated
	 */
	private String nationality;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.nation
	 *
	 * @mbg.generated
	 */
	private Integer nation;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.occupation
	 *
	 * @mbg.generated
	 */
	private Integer occupation;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.mobile
	 *
	 * @mbg.generated
	 */
	private String mobile;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.marital_status
	 *
	 * @mbg.generated
	 */
	private Integer maritalStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.account_address
	 *
	 * @mbg.generated
	 */
	private String accountAddress;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.management_community
	 *
	 * @mbg.generated
	 */
	private String managementCommunity;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.present_address
	 *
	 * @mbg.generated
	 */
	private String presentAddress;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.create_doctor
	 *
	 * @mbg.generated
	 */
	private String createDoctor;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.permanent_address
	 *
	 * @mbg.generated
	 */
	private String permanentAddress;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.neighborhood_committee
	 *
	 * @mbg.generated
	 */
	private String neighborhoodCommittee;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.district_county
	 *
	 * @mbg.generated
	 */
	private String districtCounty;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.husband_name
	 *
	 * @mbg.generated
	 */
	private String husbandName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.husband_age
	 *
	 * @mbg.generated
	 */
	private Integer husbandAge;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.husband_mobile
	 *
	 * @mbg.generated
	 */
	private String husbandMobile;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.husband_card_id
	 *
	 * @mbg.generated
	 */
	private String husbandCardId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.husband_single
	 *
	 * @mbg.generated
	 */
	private Integer husbandSingle;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.husband_account_address
	 *
	 * @mbg.generated
	 */
	private String husbandAccountAddress;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.husband_present_address
	 *
	 * @mbg.generated
	 */
	private String husbandPresentAddress;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.husband_replace
	 *
	 * @mbg.generated
	 */
	private Integer husbandReplace;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.husband_building_address
	 *
	 * @mbg.generated
	 */
	private String husbandBuildingAddress;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.husband_building_area
	 *
	 * @mbg.generated
	 */
	private String husbandBuildingArea;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.examination_address
	 *
	 * @mbg.generated
	 */
	private String examinationAddress;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.is_farmer
	 *
	 * @mbg.generated
	 */
	private Integer isFarmer;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.is_childbirth_allowance
	 *
	 * @mbg.generated
	 */
	private Integer isChildbirthAllowance;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.resting_place
	 *
	 * @mbg.generated
	 */
	private String restingPlace;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.in_out_segment
	 *
	 * @mbg.generated
	 */
	private String inOutSegment;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.is_prenatal_examination
	 *
	 * @mbg.generated
	 */
	private Integer isPrenatalExamination;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.is_more_six_months
	 *
	 * @mbg.generated
	 */
	private Integer isMoreSixMonths;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.is_more_one_year
	 *
	 * @mbg.generated
	 */
	private Integer isMoreOneYear;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.is_HIV_detection_card
	 *
	 * @mbg.generated
	 */
	private Integer isHivDetectionCard;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.screening_results
	 *
	 * @mbg.generated
	 */
	private String screeningResults;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.is_high_risk_factor
	 *
	 * @mbg.generated
	 */
	private Integer isHighRiskFactor;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.height
	 *
	 * @mbg.generated
	 */
	private String height;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.pre_pregnancy_weight
	 *
	 * @mbg.generated
	 */
	private String prePregnancyWeight;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.BMI_index
	 *
	 * @mbg.generated
	 */
	private String bmiIndex;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.BMI_type
	 *
	 * @mbg.generated
	 */
	private String bmiType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.blood_pressure
	 *
	 * @mbg.generated
	 */
	private String bloodPressure;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.last_menstruation
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	private Date lastMenstruation;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.diagnosis_date
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	private Date diagnosisDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.gestational_weeks
	 *
	 * @mbg.generated
	 */
	private String gestationalWeeks;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.pregnancy_birth
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	private Date pregnancyBirth;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.is_B_verification
	 *
	 * @mbg.generated
	 */
	private Integer isBVerification;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.verifying_pregnancy
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	private Date verifyingPregnancy;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.verifying_last_menstruation
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	private Date verifyingLastMenstruation;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.books_gestational_weeks
	 *
	 * @mbg.generated
	 */
	private String booksGestationalWeeks;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.pregnancy_times
	 *
	 * @mbg.generated
	 */
	private String pregnancyTimes;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.production_times
	 *
	 * @mbg.generated
	 */
	private String productionTimes;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.vaginal_delivery_times
	 *
	 * @mbg.generated
	 */
	private String vaginalDeliveryTimes;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.planing_palace_times
	 *
	 * @mbg.generated
	 */
	private String planingPalaceTimes;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.natural_abortion_times
	 *
	 * @mbg.generated
	 */
	private String naturalAbortionTimes;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.no_natural_abortion_times
	 *
	 * @mbg.generated
	 */
	private String noNaturalAbortionTimes;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.gestation_times
	 *
	 * @mbg.generated
	 */
	private String gestationTimes;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.is_folic_acid
	 *
	 * @mbg.generated
	 */
	private Integer isFolicAcid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.is_law
	 *
	 * @mbg.generated
	 */
	private Integer isLaw;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.medicine_type
	 *
	 * @mbg.generated
	 */
	private String medicineType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.medicine_time
	 *
	 * @mbg.generated
	 */
	private Integer medicineTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.family_history
	 *
	 * @mbg.generated
	 */
	private String familyHistory;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.personal_history
	 *
	 * @mbg.generated
	 */
	private String personalHistory;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.past_history
	 *
	 * @mbg.generated
	 */
	private String pastHistory;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.is_high_risk
	 *
	 * @mbg.generated
	 */
	private Integer isHighRisk;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.health_care_guidance
	 *
	 * @mbg.generated
	 */
	private String healthCareGuidance;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.appointment_time
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	private Date appointmentTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.create_time
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.update_time
	 *
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.sign_time
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	private Date signTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.expiration_date
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	private Date expirationDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.in_use
	 *
	 * @mbg.generated
	 */
	private Integer inUse;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_motherhood_user.manager_id
	 *
	 * @mbg.generated
	 */
	private String managerId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.id
	 *
	 * @return the value of api_motherhood_user.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.id
	 *
	 * @param id
	 *            the value for api_motherhood_user.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.created_date
	 *
	 * @return the value of api_motherhood_user.created_date
	 *
	 * @mbg.generated
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.created_date
	 *
	 * @param createdDate
	 *            the value for api_motherhood_user.created_date
	 *
	 * @mbg.generated
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.document_type
	 *
	 * @return the value of api_motherhood_user.document_type
	 *
	 * @mbg.generated
	 */
	public Integer getDocumentType() {
		return documentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.document_type
	 *
	 * @param documentType
	 *            the value for api_motherhood_user.document_type
	 *
	 * @mbg.generated
	 */
	public void setDocumentType(Integer documentType) {
		this.documentType = documentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.document_code
	 *
	 * @return the value of api_motherhood_user.document_code
	 *
	 * @mbg.generated
	 */
	public String getDocumentCode() {
		return documentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.document_code
	 *
	 * @param documentCode
	 *            the value for api_motherhood_user.document_code
	 *
	 * @mbg.generated
	 */
	public void setDocumentCode(String documentCode) {
		this.documentCode = documentCode == null ? null : documentCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.name
	 *
	 * @return the value of api_motherhood_user.name
	 *
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.name
	 *
	 * @param name
	 *            the value for api_motherhood_user.name
	 *
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.birthday
	 *
	 * @return the value of api_motherhood_user.birthday
	 *
	 * @mbg.generated
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.birthday
	 *
	 * @param birthday
	 *            the value for api_motherhood_user.birthday
	 *
	 * @mbg.generated
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.age
	 *
	 * @return the value of api_motherhood_user.age
	 *
	 * @mbg.generated
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.age
	 *
	 * @param age
	 *            the value for api_motherhood_user.age
	 *
	 * @mbg.generated
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.cultural_status
	 *
	 * @return the value of api_motherhood_user.cultural_status
	 *
	 * @mbg.generated
	 */
	public Integer getCulturalStatus() {
		return culturalStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.cultural_status
	 *
	 * @param culturalStatus
	 *            the value for api_motherhood_user.cultural_status
	 *
	 * @mbg.generated
	 */
	public void setCulturalStatus(Integer culturalStatus) {
		this.culturalStatus = culturalStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.nationality
	 *
	 * @return the value of api_motherhood_user.nationality
	 *
	 * @mbg.generated
	 */
	public String getNationality() {
		return nationality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.nationality
	 *
	 * @param nationality
	 *            the value for api_motherhood_user.nationality
	 *
	 * @mbg.generated
	 */
	public void setNationality(String nationality) {
		this.nationality = nationality == null ? null : nationality.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.nation
	 *
	 * @return the value of api_motherhood_user.nation
	 *
	 * @mbg.generated
	 */
	public Integer getNation() {
		return nation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.nation
	 *
	 * @param nation
	 *            the value for api_motherhood_user.nation
	 *
	 * @mbg.generated
	 */
	public void setNation(Integer nation) {
		this.nation = nation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.occupation
	 *
	 * @return the value of api_motherhood_user.occupation
	 *
	 * @mbg.generated
	 */
	public Integer getOccupation() {
		return occupation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.occupation
	 *
	 * @param occupation
	 *            the value for api_motherhood_user.occupation
	 *
	 * @mbg.generated
	 */
	public void setOccupation(Integer occupation) {
		this.occupation = occupation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.mobile
	 *
	 * @return the value of api_motherhood_user.mobile
	 *
	 * @mbg.generated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.mobile
	 *
	 * @param mobile
	 *            the value for api_motherhood_user.mobile
	 *
	 * @mbg.generated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.marital_status
	 *
	 * @return the value of api_motherhood_user.marital_status
	 *
	 * @mbg.generated
	 */
	public Integer getMaritalStatus() {
		return maritalStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.marital_status
	 *
	 * @param maritalStatus
	 *            the value for api_motherhood_user.marital_status
	 *
	 * @mbg.generated
	 */
	public void setMaritalStatus(Integer maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.account_address
	 *
	 * @return the value of api_motherhood_user.account_address
	 *
	 * @mbg.generated
	 */
	public String getAccountAddress() {
		return accountAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.account_address
	 *
	 * @param accountAddress
	 *            the value for api_motherhood_user.account_address
	 *
	 * @mbg.generated
	 */
	public void setAccountAddress(String accountAddress) {
		this.accountAddress = accountAddress == null ? null : accountAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.management_community
	 *
	 * @return the value of api_motherhood_user.management_community
	 *
	 * @mbg.generated
	 */
	public String getManagementCommunity() {
		return managementCommunity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.management_community
	 *
	 * @param managementCommunity
	 *            the value for api_motherhood_user.management_community
	 *
	 * @mbg.generated
	 */
	public void setManagementCommunity(String managementCommunity) {
		this.managementCommunity = managementCommunity == null ? null : managementCommunity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.present_address
	 *
	 * @return the value of api_motherhood_user.present_address
	 *
	 * @mbg.generated
	 */
	public String getPresentAddress() {
		return presentAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.present_address
	 *
	 * @param presentAddress
	 *            the value for api_motherhood_user.present_address
	 *
	 * @mbg.generated
	 */
	public void setPresentAddress(String presentAddress) {
		this.presentAddress = presentAddress == null ? null : presentAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.create_doctor
	 *
	 * @return the value of api_motherhood_user.create_doctor
	 *
	 * @mbg.generated
	 */
	public String getCreateDoctor() {
		return createDoctor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.create_doctor
	 *
	 * @param createDoctor
	 *            the value for api_motherhood_user.create_doctor
	 *
	 * @mbg.generated
	 */
	public void setCreateDoctor(String createDoctor) {
		this.createDoctor = createDoctor == null ? null : createDoctor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.permanent_address
	 *
	 * @return the value of api_motherhood_user.permanent_address
	 *
	 * @mbg.generated
	 */
	public String getPermanentAddress() {
		return permanentAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.permanent_address
	 *
	 * @param permanentAddress
	 *            the value for api_motherhood_user.permanent_address
	 *
	 * @mbg.generated
	 */
	public void setPermanentAddress(String permanentAddress) {
		this.permanentAddress = permanentAddress == null ? null : permanentAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.neighborhood_committee
	 *
	 * @return the value of api_motherhood_user.neighborhood_committee
	 *
	 * @mbg.generated
	 */
	public String getNeighborhoodCommittee() {
		return neighborhoodCommittee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.neighborhood_committee
	 *
	 * @param neighborhoodCommittee
	 *            the value for api_motherhood_user.neighborhood_committee
	 *
	 * @mbg.generated
	 */
	public void setNeighborhoodCommittee(String neighborhoodCommittee) {
		this.neighborhoodCommittee = neighborhoodCommittee == null ? null
				: neighborhoodCommittee.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.district_county
	 *
	 * @return the value of api_motherhood_user.district_county
	 *
	 * @mbg.generated
	 */
	public String getDistrictCounty() {
		return districtCounty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.district_county
	 *
	 * @param districtCounty
	 *            the value for api_motherhood_user.district_county
	 *
	 * @mbg.generated
	 */
	public void setDistrictCounty(String districtCounty) {
		this.districtCounty = districtCounty == null ? null : districtCounty.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.husband_name
	 *
	 * @return the value of api_motherhood_user.husband_name
	 *
	 * @mbg.generated
	 */
	public String getHusbandName() {
		return husbandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.husband_name
	 *
	 * @param husbandName
	 *            the value for api_motherhood_user.husband_name
	 *
	 * @mbg.generated
	 */
	public void setHusbandName(String husbandName) {
		this.husbandName = husbandName == null ? null : husbandName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.husband_age
	 *
	 * @return the value of api_motherhood_user.husband_age
	 *
	 * @mbg.generated
	 */
	public Integer getHusbandAge() {
		return husbandAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.husband_age
	 *
	 * @param husbandAge
	 *            the value for api_motherhood_user.husband_age
	 *
	 * @mbg.generated
	 */
	public void setHusbandAge(Integer husbandAge) {
		this.husbandAge = husbandAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.husband_mobile
	 *
	 * @return the value of api_motherhood_user.husband_mobile
	 *
	 * @mbg.generated
	 */
	public String getHusbandMobile() {
		return husbandMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.husband_mobile
	 *
	 * @param husbandMobile
	 *            the value for api_motherhood_user.husband_mobile
	 *
	 * @mbg.generated
	 */
	public void setHusbandMobile(String husbandMobile) {
		this.husbandMobile = husbandMobile == null ? null : husbandMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.husband_card_id
	 *
	 * @return the value of api_motherhood_user.husband_card_id
	 *
	 * @mbg.generated
	 */
	public String getHusbandCardId() {
		return husbandCardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.husband_card_id
	 *
	 * @param husbandCardId
	 *            the value for api_motherhood_user.husband_card_id
	 *
	 * @mbg.generated
	 */
	public void setHusbandCardId(String husbandCardId) {
		this.husbandCardId = husbandCardId == null ? null : husbandCardId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.husband_single
	 *
	 * @return the value of api_motherhood_user.husband_single
	 *
	 * @mbg.generated
	 */
	public Integer getHusbandSingle() {
		return husbandSingle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.husband_single
	 *
	 * @param husbandSingle
	 *            the value for api_motherhood_user.husband_single
	 *
	 * @mbg.generated
	 */
	public void setHusbandSingle(Integer husbandSingle) {
		this.husbandSingle = husbandSingle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.husband_account_address
	 *
	 * @return the value of api_motherhood_user.husband_account_address
	 *
	 * @mbg.generated
	 */
	public String getHusbandAccountAddress() {
		return husbandAccountAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.husband_account_address
	 *
	 * @param husbandAccountAddress
	 *            the value for api_motherhood_user.husband_account_address
	 *
	 * @mbg.generated
	 */
	public void setHusbandAccountAddress(String husbandAccountAddress) {
		this.husbandAccountAddress = husbandAccountAddress == null ? null
				: husbandAccountAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.husband_present_address
	 *
	 * @return the value of api_motherhood_user.husband_present_address
	 *
	 * @mbg.generated
	 */
	public String getHusbandPresentAddress() {
		return husbandPresentAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.husband_present_address
	 *
	 * @param husbandPresentAddress
	 *            the value for api_motherhood_user.husband_present_address
	 *
	 * @mbg.generated
	 */
	public void setHusbandPresentAddress(String husbandPresentAddress) {
		this.husbandPresentAddress = husbandPresentAddress == null ? null
				: husbandPresentAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.husband_replace
	 *
	 * @return the value of api_motherhood_user.husband_replace
	 *
	 * @mbg.generated
	 */
	public Integer getHusbandReplace() {
		return husbandReplace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.husband_replace
	 *
	 * @param husbandReplace
	 *            the value for api_motherhood_user.husband_replace
	 *
	 * @mbg.generated
	 */
	public void setHusbandReplace(Integer husbandReplace) {
		this.husbandReplace = husbandReplace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.husband_building_address
	 *
	 * @return the value of api_motherhood_user.husband_building_address
	 *
	 * @mbg.generated
	 */
	public String getHusbandBuildingAddress() {
		return husbandBuildingAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.husband_building_address
	 *
	 * @param husbandBuildingAddress
	 *            the value for api_motherhood_user.husband_building_address
	 *
	 * @mbg.generated
	 */
	public void setHusbandBuildingAddress(String husbandBuildingAddress) {
		this.husbandBuildingAddress = husbandBuildingAddress == null ? null
				: husbandBuildingAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.husband_building_area
	 *
	 * @return the value of api_motherhood_user.husband_building_area
	 *
	 * @mbg.generated
	 */
	public String getHusbandBuildingArea() {
		return husbandBuildingArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.husband_building_area
	 *
	 * @param husbandBuildingArea
	 *            the value for api_motherhood_user.husband_building_area
	 *
	 * @mbg.generated
	 */
	public void setHusbandBuildingArea(String husbandBuildingArea) {
		this.husbandBuildingArea = husbandBuildingArea == null ? null : husbandBuildingArea.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.examination_address
	 *
	 * @return the value of api_motherhood_user.examination_address
	 *
	 * @mbg.generated
	 */
	public String getExaminationAddress() {
		return examinationAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.examination_address
	 *
	 * @param examinationAddress
	 *            the value for api_motherhood_user.examination_address
	 *
	 * @mbg.generated
	 */
	public void setExaminationAddress(String examinationAddress) {
		this.examinationAddress = examinationAddress == null ? null : examinationAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.is_farmer
	 *
	 * @return the value of api_motherhood_user.is_farmer
	 *
	 * @mbg.generated
	 */
	public Integer getIsFarmer() {
		return isFarmer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.is_farmer
	 *
	 * @param isFarmer
	 *            the value for api_motherhood_user.is_farmer
	 *
	 * @mbg.generated
	 */
	public void setIsFarmer(Integer isFarmer) {
		this.isFarmer = isFarmer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.is_childbirth_allowance
	 *
	 * @return the value of api_motherhood_user.is_childbirth_allowance
	 *
	 * @mbg.generated
	 */
	public Integer getIsChildbirthAllowance() {
		return isChildbirthAllowance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.is_childbirth_allowance
	 *
	 * @param isChildbirthAllowance
	 *            the value for api_motherhood_user.is_childbirth_allowance
	 *
	 * @mbg.generated
	 */
	public void setIsChildbirthAllowance(Integer isChildbirthAllowance) {
		this.isChildbirthAllowance = isChildbirthAllowance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.resting_place
	 *
	 * @return the value of api_motherhood_user.resting_place
	 *
	 * @mbg.generated
	 */
	public String getRestingPlace() {
		return restingPlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.resting_place
	 *
	 * @param restingPlace
	 *            the value for api_motherhood_user.resting_place
	 *
	 * @mbg.generated
	 */
	public void setRestingPlace(String restingPlace) {
		this.restingPlace = restingPlace == null ? null : restingPlace.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.in_out_segment
	 *
	 * @return the value of api_motherhood_user.in_out_segment
	 *
	 * @mbg.generated
	 */
	public String getInOutSegment() {
		return inOutSegment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.in_out_segment
	 *
	 * @param inOutSegment
	 *            the value for api_motherhood_user.in_out_segment
	 *
	 * @mbg.generated
	 */
	public void setInOutSegment(String inOutSegment) {
		this.inOutSegment = inOutSegment == null ? null : inOutSegment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.is_prenatal_examination
	 *
	 * @return the value of api_motherhood_user.is_prenatal_examination
	 *
	 * @mbg.generated
	 */
	public Integer getIsPrenatalExamination() {
		return isPrenatalExamination;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.is_prenatal_examination
	 *
	 * @param isPrenatalExamination
	 *            the value for api_motherhood_user.is_prenatal_examination
	 *
	 * @mbg.generated
	 */
	public void setIsPrenatalExamination(Integer isPrenatalExamination) {
		this.isPrenatalExamination = isPrenatalExamination;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.is_more_six_months
	 *
	 * @return the value of api_motherhood_user.is_more_six_months
	 *
	 * @mbg.generated
	 */
	public Integer getIsMoreSixMonths() {
		return isMoreSixMonths;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.is_more_six_months
	 *
	 * @param isMoreSixMonths
	 *            the value for api_motherhood_user.is_more_six_months
	 *
	 * @mbg.generated
	 */
	public void setIsMoreSixMonths(Integer isMoreSixMonths) {
		this.isMoreSixMonths = isMoreSixMonths;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.is_more_one_year
	 *
	 * @return the value of api_motherhood_user.is_more_one_year
	 *
	 * @mbg.generated
	 */
	public Integer getIsMoreOneYear() {
		return isMoreOneYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.is_more_one_year
	 *
	 * @param isMoreOneYear
	 *            the value for api_motherhood_user.is_more_one_year
	 *
	 * @mbg.generated
	 */
	public void setIsMoreOneYear(Integer isMoreOneYear) {
		this.isMoreOneYear = isMoreOneYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.is_HIV_detection_card
	 *
	 * @return the value of api_motherhood_user.is_HIV_detection_card
	 *
	 * @mbg.generated
	 */
	public Integer getIsHivDetectionCard() {
		return isHivDetectionCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.is_HIV_detection_card
	 *
	 * @param isHivDetectionCard
	 *            the value for api_motherhood_user.is_HIV_detection_card
	 *
	 * @mbg.generated
	 */
	public void setIsHivDetectionCard(Integer isHivDetectionCard) {
		this.isHivDetectionCard = isHivDetectionCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.screening_results
	 *
	 * @return the value of api_motherhood_user.screening_results
	 *
	 * @mbg.generated
	 */
	public String getScreeningResults() {
		return screeningResults;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.screening_results
	 *
	 * @param screeningResults
	 *            the value for api_motherhood_user.screening_results
	 *
	 * @mbg.generated
	 */
	public void setScreeningResults(String screeningResults) {
		this.screeningResults = screeningResults == null ? null : screeningResults.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.is_high_risk_factor
	 *
	 * @return the value of api_motherhood_user.is_high_risk_factor
	 *
	 * @mbg.generated
	 */
	public Integer getIsHighRiskFactor() {
		return isHighRiskFactor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.is_high_risk_factor
	 *
	 * @param isHighRiskFactor
	 *            the value for api_motherhood_user.is_high_risk_factor
	 *
	 * @mbg.generated
	 */
	public void setIsHighRiskFactor(Integer isHighRiskFactor) {
		this.isHighRiskFactor = isHighRiskFactor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.height
	 *
	 * @return the value of api_motherhood_user.height
	 *
	 * @mbg.generated
	 */
	public String getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.height
	 *
	 * @param height
	 *            the value for api_motherhood_user.height
	 *
	 * @mbg.generated
	 */
	public void setHeight(String height) {
		this.height = height == null ? null : height.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.pre_pregnancy_weight
	 *
	 * @return the value of api_motherhood_user.pre_pregnancy_weight
	 *
	 * @mbg.generated
	 */
	public String getPrePregnancyWeight() {
		return prePregnancyWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.pre_pregnancy_weight
	 *
	 * @param prePregnancyWeight
	 *            the value for api_motherhood_user.pre_pregnancy_weight
	 *
	 * @mbg.generated
	 */
	public void setPrePregnancyWeight(String prePregnancyWeight) {
		this.prePregnancyWeight = prePregnancyWeight == null ? null : prePregnancyWeight.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.BMI_index
	 *
	 * @return the value of api_motherhood_user.BMI_index
	 *
	 * @mbg.generated
	 */
	public String getBmiIndex() {
		return bmiIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.BMI_index
	 *
	 * @param bmiIndex
	 *            the value for api_motherhood_user.BMI_index
	 *
	 * @mbg.generated
	 */
	public void setBmiIndex(String bmiIndex) {
		this.bmiIndex = bmiIndex == null ? null : bmiIndex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.BMI_type
	 *
	 * @return the value of api_motherhood_user.BMI_type
	 *
	 * @mbg.generated
	 */
	public String getBmiType() {
		return bmiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.BMI_type
	 *
	 * @param bmiType
	 *            the value for api_motherhood_user.BMI_type
	 *
	 * @mbg.generated
	 */
	public void setBmiType(String bmiType) {
		this.bmiType = bmiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.blood_pressure
	 *
	 * @return the value of api_motherhood_user.blood_pressure
	 *
	 * @mbg.generated
	 */
	public String getBloodPressure() {
		return bloodPressure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.blood_pressure
	 *
	 * @param bloodPressure
	 *            the value for api_motherhood_user.blood_pressure
	 *
	 * @mbg.generated
	 */
	public void setBloodPressure(String bloodPressure) {
		this.bloodPressure = bloodPressure == null ? null : bloodPressure.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.last_menstruation
	 *
	 * @return the value of api_motherhood_user.last_menstruation
	 *
	 * @mbg.generated
	 */
	public Date getLastMenstruation() {
		return lastMenstruation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.last_menstruation
	 *
	 * @param lastMenstruation
	 *            the value for api_motherhood_user.last_menstruation
	 *
	 * @mbg.generated
	 */
	public void setLastMenstruation(Date lastMenstruation) {
		this.lastMenstruation = lastMenstruation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.diagnosis_date
	 *
	 * @return the value of api_motherhood_user.diagnosis_date
	 *
	 * @mbg.generated
	 */
	public Date getDiagnosisDate() {
		return diagnosisDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.diagnosis_date
	 *
	 * @param diagnosisDate
	 *            the value for api_motherhood_user.diagnosis_date
	 *
	 * @mbg.generated
	 */
	public void setDiagnosisDate(Date diagnosisDate) {
		this.diagnosisDate = diagnosisDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.gestational_weeks
	 *
	 * @return the value of api_motherhood_user.gestational_weeks
	 *
	 * @mbg.generated
	 */
	public String getGestationalWeeks() {
		return gestationalWeeks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.gestational_weeks
	 *
	 * @param gestationalWeeks
	 *            the value for api_motherhood_user.gestational_weeks
	 *
	 * @mbg.generated
	 */
	public void setGestationalWeeks(String gestationalWeeks) {
		this.gestationalWeeks = gestationalWeeks == null ? null : gestationalWeeks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.pregnancy_birth
	 *
	 * @return the value of api_motherhood_user.pregnancy_birth
	 *
	 * @mbg.generated
	 */
	public Date getPregnancyBirth() {
		return pregnancyBirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.pregnancy_birth
	 *
	 * @param pregnancyBirth
	 *            the value for api_motherhood_user.pregnancy_birth
	 *
	 * @mbg.generated
	 */
	public void setPregnancyBirth(Date pregnancyBirth) {
		this.pregnancyBirth = pregnancyBirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.is_B_verification
	 *
	 * @return the value of api_motherhood_user.is_B_verification
	 *
	 * @mbg.generated
	 */
	public Integer getIsBVerification() {
		return isBVerification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.is_B_verification
	 *
	 * @param isBVerification
	 *            the value for api_motherhood_user.is_B_verification
	 *
	 * @mbg.generated
	 */
	public void setIsBVerification(Integer isBVerification) {
		this.isBVerification = isBVerification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.verifying_pregnancy
	 *
	 * @return the value of api_motherhood_user.verifying_pregnancy
	 *
	 * @mbg.generated
	 */
	public Date getVerifyingPregnancy() {
		return verifyingPregnancy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.verifying_pregnancy
	 *
	 * @param verifyingPregnancy
	 *            the value for api_motherhood_user.verifying_pregnancy
	 *
	 * @mbg.generated
	 */
	public void setVerifyingPregnancy(Date verifyingPregnancy) {
		this.verifyingPregnancy = verifyingPregnancy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * api_motherhood_user.verifying_last_menstruation
	 *
	 * @return the value of api_motherhood_user.verifying_last_menstruation
	 *
	 * @mbg.generated
	 */
	public Date getVerifyingLastMenstruation() {
		return verifyingLastMenstruation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * api_motherhood_user.verifying_last_menstruation
	 *
	 * @param verifyingLastMenstruation
	 *            the value for api_motherhood_user.verifying_last_menstruation
	 *
	 * @mbg.generated
	 */
	public void setVerifyingLastMenstruation(Date verifyingLastMenstruation) {
		this.verifyingLastMenstruation = verifyingLastMenstruation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.books_gestational_weeks
	 *
	 * @return the value of api_motherhood_user.books_gestational_weeks
	 *
	 * @mbg.generated
	 */
	public String getBooksGestationalWeeks() {
		return booksGestationalWeeks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.books_gestational_weeks
	 *
	 * @param booksGestationalWeeks
	 *            the value for api_motherhood_user.books_gestational_weeks
	 *
	 * @mbg.generated
	 */
	public void setBooksGestationalWeeks(String booksGestationalWeeks) {
		this.booksGestationalWeeks = booksGestationalWeeks == null ? null
				: booksGestationalWeeks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.pregnancy_times
	 *
	 * @return the value of api_motherhood_user.pregnancy_times
	 *
	 * @mbg.generated
	 */
	public String getPregnancyTimes() {
		return pregnancyTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.pregnancy_times
	 *
	 * @param pregnancyTimes
	 *            the value for api_motherhood_user.pregnancy_times
	 *
	 * @mbg.generated
	 */
	public void setPregnancyTimes(String pregnancyTimes) {
		this.pregnancyTimes = pregnancyTimes == null ? null : pregnancyTimes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.production_times
	 *
	 * @return the value of api_motherhood_user.production_times
	 *
	 * @mbg.generated
	 */
	public String getProductionTimes() {
		return productionTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.production_times
	 *
	 * @param productionTimes
	 *            the value for api_motherhood_user.production_times
	 *
	 * @mbg.generated
	 */
	public void setProductionTimes(String productionTimes) {
		this.productionTimes = productionTimes == null ? null : productionTimes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.vaginal_delivery_times
	 *
	 * @return the value of api_motherhood_user.vaginal_delivery_times
	 *
	 * @mbg.generated
	 */
	public String getVaginalDeliveryTimes() {
		return vaginalDeliveryTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.vaginal_delivery_times
	 *
	 * @param vaginalDeliveryTimes
	 *            the value for api_motherhood_user.vaginal_delivery_times
	 *
	 * @mbg.generated
	 */
	public void setVaginalDeliveryTimes(String vaginalDeliveryTimes) {
		this.vaginalDeliveryTimes = vaginalDeliveryTimes == null ? null
				: vaginalDeliveryTimes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.planing_palace_times
	 *
	 * @return the value of api_motherhood_user.planing_palace_times
	 *
	 * @mbg.generated
	 */
	public String getPlaningPalaceTimes() {
		return planingPalaceTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.planing_palace_times
	 *
	 * @param planingPalaceTimes
	 *            the value for api_motherhood_user.planing_palace_times
	 *
	 * @mbg.generated
	 */
	public void setPlaningPalaceTimes(String planingPalaceTimes) {
		this.planingPalaceTimes = planingPalaceTimes == null ? null : planingPalaceTimes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.natural_abortion_times
	 *
	 * @return the value of api_motherhood_user.natural_abortion_times
	 *
	 * @mbg.generated
	 */
	public String getNaturalAbortionTimes() {
		return naturalAbortionTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.natural_abortion_times
	 *
	 * @param naturalAbortionTimes
	 *            the value for api_motherhood_user.natural_abortion_times
	 *
	 * @mbg.generated
	 */
	public void setNaturalAbortionTimes(String naturalAbortionTimes) {
		this.naturalAbortionTimes = naturalAbortionTimes == null ? null
				: naturalAbortionTimes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * api_motherhood_user.no_natural_abortion_times
	 *
	 * @return the value of api_motherhood_user.no_natural_abortion_times
	 *
	 * @mbg.generated
	 */
	public String getNoNaturalAbortionTimes() {
		return noNaturalAbortionTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * api_motherhood_user.no_natural_abortion_times
	 *
	 * @param noNaturalAbortionTimes
	 *            the value for api_motherhood_user.no_natural_abortion_times
	 *
	 * @mbg.generated
	 */
	public void setNoNaturalAbortionTimes(String noNaturalAbortionTimes) {
		this.noNaturalAbortionTimes = noNaturalAbortionTimes == null ? null
				: noNaturalAbortionTimes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.gestation_times
	 *
	 * @return the value of api_motherhood_user.gestation_times
	 *
	 * @mbg.generated
	 */
	public String getGestationTimes() {
		return gestationTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.gestation_times
	 *
	 * @param gestationTimes
	 *            the value for api_motherhood_user.gestation_times
	 *
	 * @mbg.generated
	 */
	public void setGestationTimes(String gestationTimes) {
		this.gestationTimes = gestationTimes == null ? null : gestationTimes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.is_folic_acid
	 *
	 * @return the value of api_motherhood_user.is_folic_acid
	 *
	 * @mbg.generated
	 */
	public Integer getIsFolicAcid() {
		return isFolicAcid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.is_folic_acid
	 *
	 * @param isFolicAcid
	 *            the value for api_motherhood_user.is_folic_acid
	 *
	 * @mbg.generated
	 */
	public void setIsFolicAcid(Integer isFolicAcid) {
		this.isFolicAcid = isFolicAcid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.is_law
	 *
	 * @return the value of api_motherhood_user.is_law
	 *
	 * @mbg.generated
	 */
	public Integer getIsLaw() {
		return isLaw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.is_law
	 *
	 * @param isLaw
	 *            the value for api_motherhood_user.is_law
	 *
	 * @mbg.generated
	 */
	public void setIsLaw(Integer isLaw) {
		this.isLaw = isLaw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.medicine_type
	 *
	 * @return the value of api_motherhood_user.medicine_type
	 *
	 * @mbg.generated
	 */
	public String getMedicineType() {
		return medicineType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.medicine_type
	 *
	 * @param medicineType
	 *            the value for api_motherhood_user.medicine_type
	 *
	 * @mbg.generated
	 */
	public void setMedicineType(String medicineType) {
		this.medicineType = medicineType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.medicine_time
	 *
	 * @return the value of api_motherhood_user.medicine_time
	 *
	 * @mbg.generated
	 */
	public Integer getMedicineTime() {
		return medicineTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.medicine_time
	 *
	 * @param medicineTime
	 *            the value for api_motherhood_user.medicine_time
	 *
	 * @mbg.generated
	 */
	public void setMedicineTime(Integer medicineTime) {
		this.medicineTime = medicineTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.family_history
	 *
	 * @return the value of api_motherhood_user.family_history
	 *
	 * @mbg.generated
	 */
	public String getFamilyHistory() {
		return familyHistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.family_history
	 *
	 * @param familyHistory
	 *            the value for api_motherhood_user.family_history
	 *
	 * @mbg.generated
	 */
	public void setFamilyHistory(String familyHistory) {
		this.familyHistory = familyHistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.personal_history
	 *
	 * @return the value of api_motherhood_user.personal_history
	 *
	 * @mbg.generated
	 */
	public String getPersonalHistory() {
		return personalHistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.personal_history
	 *
	 * @param personalHistory
	 *            the value for api_motherhood_user.personal_history
	 *
	 * @mbg.generated
	 */
	public void setPersonalHistory(String personalHistory) {
		this.personalHistory = personalHistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.past_history
	 *
	 * @return the value of api_motherhood_user.past_history
	 *
	 * @mbg.generated
	 */
	public String getPastHistory() {
		return pastHistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.past_history
	 *
	 * @param pastHistory
	 *            the value for api_motherhood_user.past_history
	 *
	 * @mbg.generated
	 */
	public void setPastHistory(String pastHistory) {
		this.pastHistory = pastHistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.is_high_risk
	 *
	 * @return the value of api_motherhood_user.is_high_risk
	 *
	 * @mbg.generated
	 */
	public Integer getIsHighRisk() {
		return isHighRisk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.is_high_risk
	 *
	 * @param isHighRisk
	 *            the value for api_motherhood_user.is_high_risk
	 *
	 * @mbg.generated
	 */
	public void setIsHighRisk(Integer isHighRisk) {
		this.isHighRisk = isHighRisk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.health_care_guidance
	 *
	 * @return the value of api_motherhood_user.health_care_guidance
	 *
	 * @mbg.generated
	 */
	public String getHealthCareGuidance() {
		return healthCareGuidance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.health_care_guidance
	 *
	 * @param healthCareGuidance
	 *            the value for api_motherhood_user.health_care_guidance
	 *
	 * @mbg.generated
	 */
	public void setHealthCareGuidance(String healthCareGuidance) {
		this.healthCareGuidance = healthCareGuidance == null ? null : healthCareGuidance.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.appointment_time
	 *
	 * @return the value of api_motherhood_user.appointment_time
	 *
	 * @mbg.generated
	 */
	public Date getAppointmentTime() {
		return appointmentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.appointment_time
	 *
	 * @param appointmentTime
	 *            the value for api_motherhood_user.appointment_time
	 *
	 * @mbg.generated
	 */
	public void setAppointmentTime(Date appointmentTime) {
		this.appointmentTime = appointmentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.create_time
	 *
	 * @return the value of api_motherhood_user.create_time
	 *
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.create_time
	 *
	 * @param createTime
	 *            the value for api_motherhood_user.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.update_time
	 *
	 * @return the value of api_motherhood_user.update_time
	 *
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.update_time
	 *
	 * @param updateTime
	 *            the value for api_motherhood_user.update_time
	 *
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.sign_time
	 *
	 * @return the value of api_motherhood_user.sign_time
	 *
	 * @mbg.generated
	 */
	public Date getSignTime() {
		return signTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.sign_time
	 *
	 * @param signTime
	 *            the value for api_motherhood_user.sign_time
	 *
	 * @mbg.generated
	 */
	public void setSignTime(Date signTime) {
		this.signTime = signTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.expiration_date
	 *
	 * @return the value of api_motherhood_user.expiration_date
	 *
	 * @mbg.generated
	 */
	public Date getExpirationDate() {
		return expirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.expiration_date
	 *
	 * @param expirationDate
	 *            the value for api_motherhood_user.expiration_date
	 *
	 * @mbg.generated
	 */
	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.in_use
	 *
	 * @return the value of api_motherhood_user.in_use
	 *
	 * @mbg.generated
	 */
	public Integer getInUse() {
		return inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.in_use
	 *
	 * @param inUse
	 *            the value for api_motherhood_user.in_use
	 *
	 * @mbg.generated
	 */
	public void setInUse(Integer inUse) {
		this.inUse = inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_motherhood_user.manager_id
	 *
	 * @return the value of api_motherhood_user.manager_id
	 *
	 * @mbg.generated
	 */
	public String getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_motherhood_user.manager_id
	 *
	 * @param managerId
	 *            the value for api_motherhood_user.manager_id
	 *
	 * @mbg.generated
	 */
	public void setManagerId(String managerId) {
		this.managerId = managerId == null ? null : managerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_motherhood_user
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ApiMotherhoodUser other = (ApiMotherhoodUser) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getCreatedDate() == null ? other.getCreatedDate() == null
						: this.getCreatedDate().equals(other.getCreatedDate()))
				&& (this.getDocumentType() == null ? other.getDocumentType() == null
						: this.getDocumentType().equals(other.getDocumentType()))
				&& (this.getDocumentCode() == null ? other.getDocumentCode() == null
						: this.getDocumentCode().equals(other.getDocumentCode()))
				&& (this.getName() == null ? other.getName() == null
						: this.getName().equals(other.getName()))
				&& (this.getBirthday() == null ? other.getBirthday() == null
						: this.getBirthday().equals(other.getBirthday()))
				&& (this.getAge() == null ? other.getAge() == null
						: this.getAge().equals(other.getAge()))
				&& (this.getCulturalStatus() == null ? other.getCulturalStatus() == null
						: this.getCulturalStatus().equals(other.getCulturalStatus()))
				&& (this.getNationality() == null ? other.getNationality() == null
						: this.getNationality().equals(other.getNationality()))
				&& (this.getNation() == null ? other.getNation() == null
						: this.getNation().equals(other.getNation()))
				&& (this.getOccupation() == null ? other.getOccupation() == null
						: this.getOccupation().equals(other.getOccupation()))
				&& (this.getMobile() == null ? other.getMobile() == null
						: this.getMobile().equals(other.getMobile()))
				&& (this.getMaritalStatus() == null ? other.getMaritalStatus() == null
						: this.getMaritalStatus().equals(other.getMaritalStatus()))
				&& (this.getAccountAddress() == null ? other.getAccountAddress() == null
						: this.getAccountAddress().equals(other.getAccountAddress()))
				&& (this.getManagementCommunity() == null ? other.getManagementCommunity() == null
						: this.getManagementCommunity().equals(other.getManagementCommunity()))
				&& (this.getPresentAddress() == null ? other.getPresentAddress() == null
						: this.getPresentAddress().equals(other.getPresentAddress()))
				&& (this.getCreateDoctor() == null ? other.getCreateDoctor() == null
						: this.getCreateDoctor().equals(other.getCreateDoctor()))
				&& (this.getPermanentAddress() == null ? other.getPermanentAddress() == null
						: this.getPermanentAddress().equals(other.getPermanentAddress()))
				&& (this.getNeighborhoodCommittee() == null
						? other.getNeighborhoodCommittee() == null
						: this.getNeighborhoodCommittee().equals(other.getNeighborhoodCommittee()))
				&& (this.getDistrictCounty() == null ? other.getDistrictCounty() == null
						: this.getDistrictCounty().equals(other.getDistrictCounty()))
				&& (this.getHusbandName() == null ? other.getHusbandName() == null
						: this.getHusbandName().equals(other.getHusbandName()))
				&& (this.getHusbandAge() == null ? other.getHusbandAge() == null
						: this.getHusbandAge().equals(other.getHusbandAge()))
				&& (this.getHusbandMobile() == null ? other.getHusbandMobile() == null
						: this.getHusbandMobile().equals(other.getHusbandMobile()))
				&& (this.getHusbandCardId() == null ? other.getHusbandCardId() == null
						: this.getHusbandCardId().equals(other.getHusbandCardId()))
				&& (this.getHusbandSingle() == null ? other.getHusbandSingle() == null
						: this.getHusbandSingle().equals(other.getHusbandSingle()))
				&& (this.getHusbandAccountAddress() == null
						? other.getHusbandAccountAddress() == null
						: this.getHusbandAccountAddress().equals(other.getHusbandAccountAddress()))
				&& (this.getHusbandPresentAddress() == null
						? other.getHusbandPresentAddress() == null
						: this.getHusbandPresentAddress().equals(other.getHusbandPresentAddress()))
				&& (this.getHusbandReplace() == null ? other.getHusbandReplace() == null
						: this.getHusbandReplace().equals(other.getHusbandReplace()))
				&& (this.getHusbandBuildingAddress() == null
						? other.getHusbandBuildingAddress() == null
						: this.getHusbandBuildingAddress()
								.equals(other.getHusbandBuildingAddress()))
				&& (this.getHusbandBuildingArea() == null ? other.getHusbandBuildingArea() == null
						: this.getHusbandBuildingArea().equals(other.getHusbandBuildingArea()))
				&& (this.getExaminationAddress() == null ? other.getExaminationAddress() == null
						: this.getExaminationAddress().equals(other.getExaminationAddress()))
				&& (this.getIsFarmer() == null ? other.getIsFarmer() == null
						: this.getIsFarmer().equals(other.getIsFarmer()))
				&& (this.getIsChildbirthAllowance() == null
						? other.getIsChildbirthAllowance() == null
						: this.getIsChildbirthAllowance().equals(other.getIsChildbirthAllowance()))
				&& (this.getRestingPlace() == null ? other.getRestingPlace() == null
						: this.getRestingPlace().equals(other.getRestingPlace()))
				&& (this.getInOutSegment() == null ? other.getInOutSegment() == null
						: this.getInOutSegment().equals(other.getInOutSegment()))
				&& (this.getIsPrenatalExamination() == null
						? other.getIsPrenatalExamination() == null
						: this.getIsPrenatalExamination().equals(other.getIsPrenatalExamination()))
				&& (this.getIsMoreSixMonths() == null ? other.getIsMoreSixMonths() == null
						: this.getIsMoreSixMonths().equals(other.getIsMoreSixMonths()))
				&& (this.getIsMoreOneYear() == null ? other.getIsMoreOneYear() == null
						: this.getIsMoreOneYear().equals(other.getIsMoreOneYear()))
				&& (this.getIsHivDetectionCard() == null ? other.getIsHivDetectionCard() == null
						: this.getIsHivDetectionCard().equals(other.getIsHivDetectionCard()))
				&& (this.getScreeningResults() == null ? other.getScreeningResults() == null
						: this.getScreeningResults().equals(other.getScreeningResults()))
				&& (this.getIsHighRiskFactor() == null ? other.getIsHighRiskFactor() == null
						: this.getIsHighRiskFactor().equals(other.getIsHighRiskFactor()))
				&& (this.getHeight() == null ? other.getHeight() == null
						: this.getHeight().equals(other.getHeight()))
				&& (this.getPrePregnancyWeight() == null ? other.getPrePregnancyWeight() == null
						: this.getPrePregnancyWeight().equals(other.getPrePregnancyWeight()))
				&& (this.getBmiIndex() == null ? other.getBmiIndex() == null
						: this.getBmiIndex().equals(other.getBmiIndex()))
				&& (this.getBmiType() == null ? other.getBmiType() == null
						: this.getBmiType().equals(other.getBmiType()))
				&& (this.getBloodPressure() == null ? other.getBloodPressure() == null
						: this.getBloodPressure().equals(other.getBloodPressure()))
				&& (this.getLastMenstruation() == null ? other.getLastMenstruation() == null
						: this.getLastMenstruation().equals(other.getLastMenstruation()))
				&& (this.getDiagnosisDate() == null ? other.getDiagnosisDate() == null
						: this.getDiagnosisDate().equals(other.getDiagnosisDate()))
				&& (this.getGestationalWeeks() == null ? other.getGestationalWeeks() == null
						: this.getGestationalWeeks().equals(other.getGestationalWeeks()))
				&& (this.getPregnancyBirth() == null ? other.getPregnancyBirth() == null
						: this.getPregnancyBirth().equals(other.getPregnancyBirth()))
				&& (this.getIsBVerification() == null ? other.getIsBVerification() == null
						: this.getIsBVerification().equals(other.getIsBVerification()))
				&& (this.getVerifyingPregnancy() == null ? other.getVerifyingPregnancy() == null
						: this.getVerifyingPregnancy().equals(other.getVerifyingPregnancy()))
				&& (this.getVerifyingLastMenstruation() == null
						? other.getVerifyingLastMenstruation() == null
						: this.getVerifyingLastMenstruation()
								.equals(other.getVerifyingLastMenstruation()))
				&& (this.getBooksGestationalWeeks() == null
						? other.getBooksGestationalWeeks() == null
						: this.getBooksGestationalWeeks().equals(other.getBooksGestationalWeeks()))
				&& (this.getPregnancyTimes() == null ? other.getPregnancyTimes() == null
						: this.getPregnancyTimes().equals(other.getPregnancyTimes()))
				&& (this.getProductionTimes() == null ? other.getProductionTimes() == null
						: this.getProductionTimes().equals(other.getProductionTimes()))
				&& (this.getVaginalDeliveryTimes() == null ? other.getVaginalDeliveryTimes() == null
						: this.getVaginalDeliveryTimes().equals(other.getVaginalDeliveryTimes()))
				&& (this.getPlaningPalaceTimes() == null ? other.getPlaningPalaceTimes() == null
						: this.getPlaningPalaceTimes().equals(other.getPlaningPalaceTimes()))
				&& (this.getNaturalAbortionTimes() == null ? other.getNaturalAbortionTimes() == null
						: this.getNaturalAbortionTimes().equals(other.getNaturalAbortionTimes()))
				&& (this.getNoNaturalAbortionTimes() == null
						? other.getNoNaturalAbortionTimes() == null
						: this.getNoNaturalAbortionTimes()
								.equals(other.getNoNaturalAbortionTimes()))
				&& (this.getGestationTimes() == null ? other.getGestationTimes() == null
						: this.getGestationTimes().equals(other.getGestationTimes()))
				&& (this.getIsFolicAcid() == null ? other.getIsFolicAcid() == null
						: this.getIsFolicAcid().equals(other.getIsFolicAcid()))
				&& (this.getIsLaw() == null ? other.getIsLaw() == null
						: this.getIsLaw().equals(other.getIsLaw()))
				&& (this.getMedicineType() == null ? other.getMedicineType() == null
						: this.getMedicineType().equals(other.getMedicineType()))
				&& (this.getMedicineTime() == null ? other.getMedicineTime() == null
						: this.getMedicineTime().equals(other.getMedicineTime()))
				&& (this.getFamilyHistory() == null ? other.getFamilyHistory() == null
						: this.getFamilyHistory().equals(other.getFamilyHistory()))
				&& (this.getPersonalHistory() == null ? other.getPersonalHistory() == null
						: this.getPersonalHistory().equals(other.getPersonalHistory()))
				&& (this.getPastHistory() == null ? other.getPastHistory() == null
						: this.getPastHistory().equals(other.getPastHistory()))
				&& (this.getIsHighRisk() == null ? other.getIsHighRisk() == null
						: this.getIsHighRisk().equals(other.getIsHighRisk()))
				&& (this.getHealthCareGuidance() == null ? other.getHealthCareGuidance() == null
						: this.getHealthCareGuidance().equals(other.getHealthCareGuidance()))
				&& (this.getAppointmentTime() == null ? other.getAppointmentTime() == null
						: this.getAppointmentTime().equals(other.getAppointmentTime()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getSignTime() == null ? other.getSignTime() == null
						: this.getSignTime().equals(other.getSignTime()))
				&& (this.getExpirationDate() == null ? other.getExpirationDate() == null
						: this.getExpirationDate().equals(other.getExpirationDate()))
				&& (this.getInUse() == null ? other.getInUse() == null
						: this.getInUse().equals(other.getInUse()))
				&& (this.getManagerId() == null ? other.getManagerId() == null
						: this.getManagerId().equals(other.getManagerId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_motherhood_user
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
		result = prime * result + ((getDocumentType() == null) ? 0 : getDocumentType().hashCode());
		result = prime * result + ((getDocumentCode() == null) ? 0 : getDocumentCode().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
		result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
		result = prime * result
				+ ((getCulturalStatus() == null) ? 0 : getCulturalStatus().hashCode());
		result = prime * result + ((getNationality() == null) ? 0 : getNationality().hashCode());
		result = prime * result + ((getNation() == null) ? 0 : getNation().hashCode());
		result = prime * result + ((getOccupation() == null) ? 0 : getOccupation().hashCode());
		result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
		result = prime * result
				+ ((getMaritalStatus() == null) ? 0 : getMaritalStatus().hashCode());
		result = prime * result
				+ ((getAccountAddress() == null) ? 0 : getAccountAddress().hashCode());
		result = prime * result
				+ ((getManagementCommunity() == null) ? 0 : getManagementCommunity().hashCode());
		result = prime * result
				+ ((getPresentAddress() == null) ? 0 : getPresentAddress().hashCode());
		result = prime * result + ((getCreateDoctor() == null) ? 0 : getCreateDoctor().hashCode());
		result = prime * result
				+ ((getPermanentAddress() == null) ? 0 : getPermanentAddress().hashCode());
		result = prime * result + ((getNeighborhoodCommittee() == null) ? 0
				: getNeighborhoodCommittee().hashCode());
		result = prime * result
				+ ((getDistrictCounty() == null) ? 0 : getDistrictCounty().hashCode());
		result = prime * result + ((getHusbandName() == null) ? 0 : getHusbandName().hashCode());
		result = prime * result + ((getHusbandAge() == null) ? 0 : getHusbandAge().hashCode());
		result = prime * result
				+ ((getHusbandMobile() == null) ? 0 : getHusbandMobile().hashCode());
		result = prime * result
				+ ((getHusbandCardId() == null) ? 0 : getHusbandCardId().hashCode());
		result = prime * result
				+ ((getHusbandSingle() == null) ? 0 : getHusbandSingle().hashCode());
		result = prime * result + ((getHusbandAccountAddress() == null) ? 0
				: getHusbandAccountAddress().hashCode());
		result = prime * result + ((getHusbandPresentAddress() == null) ? 0
				: getHusbandPresentAddress().hashCode());
		result = prime * result
				+ ((getHusbandReplace() == null) ? 0 : getHusbandReplace().hashCode());
		result = prime * result + ((getHusbandBuildingAddress() == null) ? 0
				: getHusbandBuildingAddress().hashCode());
		result = prime * result
				+ ((getHusbandBuildingArea() == null) ? 0 : getHusbandBuildingArea().hashCode());
		result = prime * result
				+ ((getExaminationAddress() == null) ? 0 : getExaminationAddress().hashCode());
		result = prime * result + ((getIsFarmer() == null) ? 0 : getIsFarmer().hashCode());
		result = prime * result + ((getIsChildbirthAllowance() == null) ? 0
				: getIsChildbirthAllowance().hashCode());
		result = prime * result + ((getRestingPlace() == null) ? 0 : getRestingPlace().hashCode());
		result = prime * result + ((getInOutSegment() == null) ? 0 : getInOutSegment().hashCode());
		result = prime * result + ((getIsPrenatalExamination() == null) ? 0
				: getIsPrenatalExamination().hashCode());
		result = prime * result
				+ ((getIsMoreSixMonths() == null) ? 0 : getIsMoreSixMonths().hashCode());
		result = prime * result
				+ ((getIsMoreOneYear() == null) ? 0 : getIsMoreOneYear().hashCode());
		result = prime * result
				+ ((getIsHivDetectionCard() == null) ? 0 : getIsHivDetectionCard().hashCode());
		result = prime * result
				+ ((getScreeningResults() == null) ? 0 : getScreeningResults().hashCode());
		result = prime * result
				+ ((getIsHighRiskFactor() == null) ? 0 : getIsHighRiskFactor().hashCode());
		result = prime * result + ((getHeight() == null) ? 0 : getHeight().hashCode());
		result = prime * result
				+ ((getPrePregnancyWeight() == null) ? 0 : getPrePregnancyWeight().hashCode());
		result = prime * result + ((getBmiIndex() == null) ? 0 : getBmiIndex().hashCode());
		result = prime * result + ((getBmiType() == null) ? 0 : getBmiType().hashCode());
		result = prime * result
				+ ((getBloodPressure() == null) ? 0 : getBloodPressure().hashCode());
		result = prime * result
				+ ((getLastMenstruation() == null) ? 0 : getLastMenstruation().hashCode());
		result = prime * result
				+ ((getDiagnosisDate() == null) ? 0 : getDiagnosisDate().hashCode());
		result = prime * result
				+ ((getGestationalWeeks() == null) ? 0 : getGestationalWeeks().hashCode());
		result = prime * result
				+ ((getPregnancyBirth() == null) ? 0 : getPregnancyBirth().hashCode());
		result = prime * result
				+ ((getIsBVerification() == null) ? 0 : getIsBVerification().hashCode());
		result = prime * result
				+ ((getVerifyingPregnancy() == null) ? 0 : getVerifyingPregnancy().hashCode());
		result = prime * result + ((getVerifyingLastMenstruation() == null) ? 0
				: getVerifyingLastMenstruation().hashCode());
		result = prime * result + ((getBooksGestationalWeeks() == null) ? 0
				: getBooksGestationalWeeks().hashCode());
		result = prime * result
				+ ((getPregnancyTimes() == null) ? 0 : getPregnancyTimes().hashCode());
		result = prime * result
				+ ((getProductionTimes() == null) ? 0 : getProductionTimes().hashCode());
		result = prime * result
				+ ((getVaginalDeliveryTimes() == null) ? 0 : getVaginalDeliveryTimes().hashCode());
		result = prime * result
				+ ((getPlaningPalaceTimes() == null) ? 0 : getPlaningPalaceTimes().hashCode());
		result = prime * result
				+ ((getNaturalAbortionTimes() == null) ? 0 : getNaturalAbortionTimes().hashCode());
		result = prime * result + ((getNoNaturalAbortionTimes() == null) ? 0
				: getNoNaturalAbortionTimes().hashCode());
		result = prime * result
				+ ((getGestationTimes() == null) ? 0 : getGestationTimes().hashCode());
		result = prime * result + ((getIsFolicAcid() == null) ? 0 : getIsFolicAcid().hashCode());
		result = prime * result + ((getIsLaw() == null) ? 0 : getIsLaw().hashCode());
		result = prime * result + ((getMedicineType() == null) ? 0 : getMedicineType().hashCode());
		result = prime * result + ((getMedicineTime() == null) ? 0 : getMedicineTime().hashCode());
		result = prime * result
				+ ((getFamilyHistory() == null) ? 0 : getFamilyHistory().hashCode());
		result = prime * result
				+ ((getPersonalHistory() == null) ? 0 : getPersonalHistory().hashCode());
		result = prime * result + ((getPastHistory() == null) ? 0 : getPastHistory().hashCode());
		result = prime * result + ((getIsHighRisk() == null) ? 0 : getIsHighRisk().hashCode());
		result = prime * result
				+ ((getHealthCareGuidance() == null) ? 0 : getHealthCareGuidance().hashCode());
		result = prime * result
				+ ((getAppointmentTime() == null) ? 0 : getAppointmentTime().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getSignTime() == null) ? 0 : getSignTime().hashCode());
		result = prime * result
				+ ((getExpirationDate() == null) ? 0 : getExpirationDate().hashCode());
		result = prime * result + ((getInUse() == null) ? 0 : getInUse().hashCode());
		result = prime * result + ((getManagerId() == null) ? 0 : getManagerId().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_motherhood_user
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", createdDate=").append(createdDate);
		sb.append(", documentType=").append(documentType);
		sb.append(", documentCode=").append(documentCode);
		sb.append(", name=").append(name);
		sb.append(", birthday=").append(birthday);
		sb.append(", age=").append(age);
		sb.append(", culturalStatus=").append(culturalStatus);
		sb.append(", nationality=").append(nationality);
		sb.append(", nation=").append(nation);
		sb.append(", occupation=").append(occupation);
		sb.append(", mobile=").append(mobile);
		sb.append(", maritalStatus=").append(maritalStatus);
		sb.append(", accountAddress=").append(accountAddress);
		sb.append(", managementCommunity=").append(managementCommunity);
		sb.append(", presentAddress=").append(presentAddress);
		sb.append(", createDoctor=").append(createDoctor);
		sb.append(", permanentAddress=").append(permanentAddress);
		sb.append(", neighborhoodCommittee=").append(neighborhoodCommittee);
		sb.append(", districtCounty=").append(districtCounty);
		sb.append(", husbandName=").append(husbandName);
		sb.append(", husbandAge=").append(husbandAge);
		sb.append(", husbandMobile=").append(husbandMobile);
		sb.append(", husbandCardId=").append(husbandCardId);
		sb.append(", husbandSingle=").append(husbandSingle);
		sb.append(", husbandAccountAddress=").append(husbandAccountAddress);
		sb.append(", husbandPresentAddress=").append(husbandPresentAddress);
		sb.append(", husbandReplace=").append(husbandReplace);
		sb.append(", husbandBuildingAddress=").append(husbandBuildingAddress);
		sb.append(", husbandBuildingArea=").append(husbandBuildingArea);
		sb.append(", examinationAddress=").append(examinationAddress);
		sb.append(", isFarmer=").append(isFarmer);
		sb.append(", isChildbirthAllowance=").append(isChildbirthAllowance);
		sb.append(", restingPlace=").append(restingPlace);
		sb.append(", inOutSegment=").append(inOutSegment);
		sb.append(", isPrenatalExamination=").append(isPrenatalExamination);
		sb.append(", isMoreSixMonths=").append(isMoreSixMonths);
		sb.append(", isMoreOneYear=").append(isMoreOneYear);
		sb.append(", isHivDetectionCard=").append(isHivDetectionCard);
		sb.append(", screeningResults=").append(screeningResults);
		sb.append(", isHighRiskFactor=").append(isHighRiskFactor);
		sb.append(", height=").append(height);
		sb.append(", prePregnancyWeight=").append(prePregnancyWeight);
		sb.append(", bmiIndex=").append(bmiIndex);
		sb.append(", bmiType=").append(bmiType);
		sb.append(", bloodPressure=").append(bloodPressure);
		sb.append(", lastMenstruation=").append(lastMenstruation);
		sb.append(", diagnosisDate=").append(diagnosisDate);
		sb.append(", gestationalWeeks=").append(gestationalWeeks);
		sb.append(", pregnancyBirth=").append(pregnancyBirth);
		sb.append(", isBVerification=").append(isBVerification);
		sb.append(", verifyingPregnancy=").append(verifyingPregnancy);
		sb.append(", verifyingLastMenstruation=").append(verifyingLastMenstruation);
		sb.append(", booksGestationalWeeks=").append(booksGestationalWeeks);
		sb.append(", pregnancyTimes=").append(pregnancyTimes);
		sb.append(", productionTimes=").append(productionTimes);
		sb.append(", vaginalDeliveryTimes=").append(vaginalDeliveryTimes);
		sb.append(", planingPalaceTimes=").append(planingPalaceTimes);
		sb.append(", naturalAbortionTimes=").append(naturalAbortionTimes);
		sb.append(", noNaturalAbortionTimes=").append(noNaturalAbortionTimes);
		sb.append(", gestationTimes=").append(gestationTimes);
		sb.append(", isFolicAcid=").append(isFolicAcid);
		sb.append(", isLaw=").append(isLaw);
		sb.append(", medicineType=").append(medicineType);
		sb.append(", medicineTime=").append(medicineTime);
		sb.append(", familyHistory=").append(familyHistory);
		sb.append(", personalHistory=").append(personalHistory);
		sb.append(", pastHistory=").append(pastHistory);
		sb.append(", isHighRisk=").append(isHighRisk);
		sb.append(", healthCareGuidance=").append(healthCareGuidance);
		sb.append(", appointmentTime=").append(appointmentTime);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", signTime=").append(signTime);
		sb.append(", expirationDate=").append(expirationDate);
		sb.append(", inUse=").append(inUse);
		sb.append(", managerId=").append(managerId);
		sb.append("]");
		return sb.toString();
	}
}