package com.semioe.api.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;

public class ApiUserInfo implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.manager_id
	 *
	 * @mbg.generated
	 */
	private String managerId;

	private String openId;

	private String familyHistory;

	public String getFamilyHistory() {
		return familyHistory;
	}

	public void setFamilyHistory(String familyHistory) {
		this.familyHistory = familyHistory;
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.parent_id
	 *
	 * @mbg.generated
	 */
	private String parentId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.role_id
	 *
	 * @mbg.generated
	 */
	private Integer roleId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.name
	 *
	 * @mbg.generated
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info. birthday
	 *
	 * @mbg.generated
	 */
	private Date birthday;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.sex
	 *
	 * @mbg.generated
	 */
	private String sex;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.image_url
	 *
	 * @mbg.generated
	 */
	private String imageUrl;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.address
	 *
	 * @mbg.generated
	 */
	private String height;
	private String address;

	private String city;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.company
	 *
	 * @mbg.generated
	 */
	private String company;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.email
	 *
	 * @mbg.generated
	 */
	private String email;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.mobile
	 *
	 * @mbg.generated
	 */
	private String mobile;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.create_time
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.update_time
	 *
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column api_user_info.in_use
	 *
	 * @mbg.generated
	 */
	private Integer inUse;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.manager_id
	 *
	 * @return the value of api_user_info.manager_id
	 *
	 * @mbg.generated
	 */

	public String getManagerId() {
		return managerId;
	}

	public String getHeight() {
		return height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getOpenId() {
		return openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.manager_id
	 *
	 * @param managerId
	 *            the value for api_user_info.manager_id
	 *
	 * @mbg.generated
	 */
	public void setManagerId(String managerId) {
		this.managerId = managerId == null ? null : managerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.parent_id
	 *
	 * @return the value of api_user_info.parent_id
	 *
	 * @mbg.generated
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.parent_id
	 *
	 * @param parentId
	 *            the value for api_user_info.parent_id
	 *
	 * @mbg.generated
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId == null ? null : parentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.role_id
	 *
	 * @return the value of api_user_info.role_id
	 *
	 * @mbg.generated
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.role_id
	 *
	 * @param roleId
	 *            the value for api_user_info.role_id
	 *
	 * @mbg.generated
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.name
	 *
	 * @return the value of api_user_info.name
	 *
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.name
	 *
	 * @param name
	 *            the value for api_user_info.name
	 *
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info. birthday
	 *
	 * @return the value of api_user_info. birthday
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	public Date getbirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info. birthday
	 *
	 * @param birthday
	 *            the value for api_user_info. birthday
	 *
	 * @mbg.generated
	 */
	public void setbirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.sex
	 *
	 * @return the value of api_user_info.sex
	 *
	 * @mbg.generated
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.sex
	 *
	 * @param sex
	 *            the value for api_user_info.sex
	 *
	 * @mbg.generated
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.image_url
	 *
	 * @return the value of api_user_info.image_url
	 *
	 * @mbg.generated
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.image_url
	 *
	 * @param imageUrl
	 *            the value for api_user_info.image_url
	 *
	 * @mbg.generated
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl == null ? null : imageUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.address
	 *
	 * @return the value of api_user_info.address
	 *
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.address
	 *
	 * @param address
	 *            the value for api_user_info.address
	 *
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.company
	 *
	 * @return the value of api_user_info.company
	 *
	 * @mbg.generated
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.company
	 *
	 * @param company
	 *            the value for api_user_info.company
	 *
	 * @mbg.generated
	 */
	public void setCompany(String company) {
		this.company = company == null ? null : company.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.email
	 *
	 * @return the value of api_user_info.email
	 *
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.email
	 *
	 * @param email
	 *            the value for api_user_info.email
	 *
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.mobile
	 *
	 * @return the value of api_user_info.mobile
	 *
	 * @mbg.generated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.mobile
	 *
	 * @param mobile
	 *            the value for api_user_info.mobile
	 *
	 * @mbg.generated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.create_time
	 *
	 * @return the value of api_user_info.create_time
	 *
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.create_time
	 *
	 * @param createTime
	 *            the value for api_user_info.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.update_time
	 *
	 * @return the value of api_user_info.update_time
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.update_time
	 *
	 * @param updateTime
	 *            the value for api_user_info.update_time
	 *
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column api_user_info.in_use
	 *
	 * @return the value of api_user_info.in_use
	 *
	 * @mbg.generated
	 */
	public Integer getInUse() {
		return inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column api_user_info.in_use
	 *
	 * @param inUse
	 *            the value for api_user_info.in_use
	 *
	 * @mbg.generated
	 */
	public void setInUse(Integer inUse) {
		this.inUse = inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_user_info
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ApiUserInfo other = (ApiUserInfo) that;
		return (this.getManagerId() == null ? other.getManagerId() == null
				: this.getManagerId().equals(other.getManagerId()))
				&& (this.getParentId() == null ? other.getParentId() == null
						: this.getParentId().equals(other.getParentId()))
				&& (this.getRoleId() == null ? other.getRoleId() == null
						: this.getRoleId().equals(other.getRoleId()))
				&& (this.getName() == null ? other.getName() == null
						: this.getName().equals(other.getName()))
				&& (this.getbirthday() == null ? other.getbirthday() == null
						: this.getbirthday().equals(other.getbirthday()))
				&& (this.getSex() == null ? other.getSex() == null
						: this.getSex().equals(other.getSex()))
				&& (this.getImageUrl() == null ? other.getImageUrl() == null
						: this.getImageUrl().equals(other.getImageUrl()))
				&& (this.getAddress() == null ? other.getAddress() == null
						: this.getAddress().equals(other.getAddress()))
				&& (this.getCompany() == null ? other.getCompany() == null
						: this.getCompany().equals(other.getCompany()))
				&& (this.getEmail() == null ? other.getEmail() == null
						: this.getEmail().equals(other.getEmail()))
				&& (this.getMobile() == null ? other.getMobile() == null
						: this.getMobile().equals(other.getMobile()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getInUse() == null ? other.getInUse() == null
						: this.getInUse().equals(other.getInUse()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_user_info
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getManagerId() == null) ? 0 : getManagerId().hashCode());
		result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
		result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getbirthday() == null) ? 0 : getbirthday().hashCode());
		result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
		result = prime * result + ((getImageUrl() == null) ? 0 : getImageUrl().hashCode());
		result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
		result = prime * result + ((getCompany() == null) ? 0 : getCompany().hashCode());
		result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
		result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getInUse() == null) ? 0 : getInUse().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_user_info
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", managerId=").append(managerId);
		sb.append(", parentId=").append(parentId);
		sb.append(", roleId=").append(roleId);
		sb.append(", name=").append(name);
		sb.append(", birthday=").append(birthday);
		sb.append(", sex=").append(sex);
		sb.append(", imageUrl=").append(imageUrl);
		sb.append(", address=").append(address);
		sb.append(", company=").append(company);
		sb.append(", email=").append(email);
		sb.append(", mobile=").append(mobile);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", inUse=").append(inUse);
		sb.append("]");
		return sb.toString();
	}
}