package com.semioe.api.entity;

import java.io.Serializable;

public class BackstageRoleMenuRel implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 7427662863584753573L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_role_menu_rel.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	private Integer parentId;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_role_menu_rel.role_id
	 *
	 * @mbg.generated
	 */
	private Integer roleId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_role_menu_rel.menu_id
	 *
	 * @mbg.generated
	 */
	private Integer menuId;

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column backstage_role_menu_rel.id
	 *
	 * @return the value of backstage_role_menu_rel.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column backstage_role_menu_rel.id
	 *
	 * @param id
	 *            the value for backstage_role_menu_rel.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column backstage_role_menu_rel.role_id
	 *
	 * @return the value of backstage_role_menu_rel.role_id
	 *
	 * @mbg.generated
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column backstage_role_menu_rel.role_id
	 *
	 * @param roleId
	 *            the value for backstage_role_menu_rel.role_id
	 *
	 * @mbg.generated
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column backstage_role_menu_rel.menu_id
	 *
	 * @return the value of backstage_role_menu_rel.menu_id
	 *
	 * @mbg.generated
	 */
	public Integer getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column backstage_role_menu_rel.menu_id
	 *
	 * @param menuId
	 *            the value for backstage_role_menu_rel.menu_id
	 *
	 * @mbg.generated
	 */
	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table backstage_role_menu_rel
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		BackstageRoleMenuRel other = (BackstageRoleMenuRel) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getRoleId() == null ? other.getRoleId() == null
						: this.getRoleId().equals(other.getRoleId()))
				&& (this.getMenuId() == null ? other.getMenuId() == null
						: this.getMenuId().equals(other.getMenuId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table backstage_role_menu_rel
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
		result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table backstage_role_menu_rel
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", roleId=").append(roleId);
		sb.append(", menuId=").append(menuId);
		sb.append("]");
		return sb.toString();
	}
}