package com.semioe.api.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;

public class BackstageMenuInfo implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3170236657930169267L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_menu_info.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_menu_info.name
	 *
	 * @mbg.generated
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_menu_info.url
	 *
	 * @mbg.generated
	 */
	private String url;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_menu_info.parent_id
	 *
	 * @mbg.generated
	 */
	private Integer parentId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_menu_info.create_time
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_menu_info.update_time
	 *
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	private Date updateTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_menu_info.in_use
	 *
	 * @mbg.generated
	 */
	private Integer inUse;

	private List<BackstageMenuInfo> children;

	private String type;

	public List<BackstageMenuInfo> getChildren() {
		return children;
	}

	public void setChildren(List<BackstageMenuInfo> children) {
		this.children = children;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column backstage_menu_info.id
	 *
	 * @return the value of backstage_menu_info.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column backstage_menu_info.id
	 *
	 * @param id
	 *            the value for backstage_menu_info.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column backstage_menu_info.name
	 *
	 * @return the value of backstage_menu_info.name
	 *
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column backstage_menu_info.name
	 *
	 * @param name
	 *            the value for backstage_menu_info.name
	 *
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column backstage_menu_info.url
	 *
	 * @return the value of backstage_menu_info.url
	 *
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column backstage_menu_info.url
	 *
	 * @param url
	 *            the value for backstage_menu_info.url
	 *
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column backstage_menu_info.parent_id
	 *
	 * @return the value of backstage_menu_info.parent_id
	 *
	 * @mbg.generated
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column backstage_menu_info.parent_id
	 *
	 * @param parentId
	 *            the value for backstage_menu_info.parent_id
	 *
	 * @mbg.generated
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column backstage_menu_info.create_time
	 *
	 * @return the value of backstage_menu_info.create_time
	 *
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column backstage_menu_info.create_time
	 *
	 * @param createTime
	 *            the value for backstage_menu_info.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column backstage_menu_info.update_time
	 *
	 * @return the value of backstage_menu_info.update_time
	 *
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column backstage_menu_info.update_time
	 *
	 * @param updateTime
	 *            the value for backstage_menu_info.update_time
	 *
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column backstage_menu_info.in_use
	 *
	 * @return the value of backstage_menu_info.in_use
	 *
	 * @mbg.generated
	 */
	public Integer getInUse() {
		return inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column backstage_menu_info.in_use
	 *
	 * @param inUse
	 *            the value for backstage_menu_info.in_use
	 *
	 * @mbg.generated
	 */
	public void setInUse(int inUse) {
		this.inUse = inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table backstage_menu_info
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		BackstageMenuInfo other = (BackstageMenuInfo) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null
						: this.getName().equals(other.getName()))
				&& (this.getUrl() == null ? other.getUrl() == null
						: this.getUrl().equals(other.getUrl()))
				&& (this.getParentId() == null ? other.getParentId() == null
						: this.getParentId().equals(other.getParentId()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getInUse() == null ? other.getInUse() == null
						: this.getInUse().equals(other.getInUse()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table backstage_menu_info
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
		result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getInUse() == null) ? 0 : getInUse().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table backstage_menu_info
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", name=").append(name);
		sb.append(", url=").append(url);
		sb.append(", parentId=").append(parentId);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", inUse=").append(inUse);
		sb.append("]");
		return sb.toString();
	}
}