package com.semioe.api.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Dictionary implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -8015483961877829648L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dictionary.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dictionary.item_id
	 *
	 * @mbg.generated
	 */
	private Integer itemId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dictionary.item_name
	 *
	 * @mbg.generated
	 */
	private String itemName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dictionary.item_type
	 *
	 * @mbg.generated
	 */
	private Integer itemType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dictionary.desc
	 *
	 * @mbg.generated
	 */
	private String desc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dictionary.create_time
	 *
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dictionary.update_time
	 *
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dictionary.id
	 *
	 * @return the value of dictionary.id
	 *
	 * @mbg.generated
	 */

	private List<Integer> typeList;

	public List<Integer> getTypeList() {
		return typeList;
	}

	public void setTypeList(List<Integer> typeList) {
		this.typeList = typeList;
	}

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dictionary.id
	 *
	 * @param id
	 *            the value for dictionary.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dictionary.item_id
	 *
	 * @return the value of dictionary.item_id
	 *
	 * @mbg.generated
	 */
	public Integer getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dictionary.item_id
	 *
	 * @param itemId
	 *            the value for dictionary.item_id
	 *
	 * @mbg.generated
	 */
	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dictionary.item_name
	 *
	 * @return the value of dictionary.item_name
	 *
	 * @mbg.generated
	 */
	public String getItemName() {
		return itemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dictionary.item_name
	 *
	 * @param itemName
	 *            the value for dictionary.item_name
	 *
	 * @mbg.generated
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName == null ? null : itemName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dictionary.item_type
	 *
	 * @return the value of dictionary.item_type
	 *
	 * @mbg.generated
	 */
	public Integer getItemType() {
		return itemType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dictionary.item_type
	 *
	 * @param itemType
	 *            the value for dictionary.item_type
	 *
	 * @mbg.generated
	 */
	public void setItemType(Integer itemType) {
		this.itemType = itemType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dictionary.desc
	 *
	 * @return the value of dictionary.desc
	 *
	 * @mbg.generated
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dictionary.desc
	 *
	 * @param desc
	 *            the value for dictionary.desc
	 *
	 * @mbg.generated
	 */
	public void setDesc(String desc) {
		this.desc = desc == null ? null : desc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dictionary.create_time
	 *
	 * @return the value of dictionary.create_time
	 *
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dictionary.create_time
	 *
	 * @param createTime
	 *            the value for dictionary.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dictionary.update_time
	 *
	 * @return the value of dictionary.update_time
	 *
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dictionary.update_time
	 *
	 * @param updateTime
	 *            the value for dictionary.update_time
	 *
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table dictionary
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Dictionary other = (Dictionary) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getItemId() == null ? other.getItemId() == null
						: this.getItemId().equals(other.getItemId()))
				&& (this.getItemName() == null ? other.getItemName() == null
						: this.getItemName().equals(other.getItemName()))
				&& (this.getItemType() == null ? other.getItemType() == null
						: this.getItemType().equals(other.getItemType()))
				&& (this.getDesc() == null ? other.getDesc() == null
						: this.getDesc().equals(other.getDesc()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table dictionary
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getItemId() == null) ? 0 : getItemId().hashCode());
		result = prime * result + ((getItemName() == null) ? 0 : getItemName().hashCode());
		result = prime * result + ((getItemType() == null) ? 0 : getItemType().hashCode());
		result = prime * result + ((getDesc() == null) ? 0 : getDesc().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table dictionary
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", itemId=").append(itemId);
		sb.append(", itemName=").append(itemName);
		sb.append(", itemType=").append(itemType);
		sb.append(", desc=").append(desc);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append("]");
		return sb.toString();
	}
}