package com.semioe.api.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JyOrgDocRelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	public JyOrgDocRelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOrgIdIsNull() {
			addCriterion("org_id is null");
			return (Criteria) this;
		}

		public Criteria andOrgIdIsNotNull() {
			addCriterion("org_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrgIdEqualTo(String value) {
			addCriterion("org_id =", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdNotEqualTo(String value) {
			addCriterion("org_id <>", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdGreaterThan(String value) {
			addCriterion("org_id >", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdGreaterThanOrEqualTo(String value) {
			addCriterion("org_id >=", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdLessThan(String value) {
			addCriterion("org_id <", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdLessThanOrEqualTo(String value) {
			addCriterion("org_id <=", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdLike(String value) {
			addCriterion("org_id like", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdNotLike(String value) {
			addCriterion("org_id not like", value, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdIn(List<String> values) {
			addCriterion("org_id in", values, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdNotIn(List<String> values) {
			addCriterion("org_id not in", values, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdBetween(String value1, String value2) {
			addCriterion("org_id between", value1, value2, "orgId");
			return (Criteria) this;
		}

		public Criteria andOrgIdNotBetween(String value1, String value2) {
			addCriterion("org_id not between", value1, value2, "orgId");
			return (Criteria) this;
		}

		public Criteria andDoctorIdIsNull() {
			addCriterion("doctor_id is null");
			return (Criteria) this;
		}

		public Criteria andDoctorIdIsNotNull() {
			addCriterion("doctor_id is not null");
			return (Criteria) this;
		}

		public Criteria andDoctorIdEqualTo(String value) {
			addCriterion("doctor_id =", value, "doctorId");
			return (Criteria) this;
		}

		public Criteria andDoctorIdNotEqualTo(String value) {
			addCriterion("doctor_id <>", value, "doctorId");
			return (Criteria) this;
		}

		public Criteria andDoctorIdGreaterThan(String value) {
			addCriterion("doctor_id >", value, "doctorId");
			return (Criteria) this;
		}

		public Criteria andDoctorIdGreaterThanOrEqualTo(String value) {
			addCriterion("doctor_id >=", value, "doctorId");
			return (Criteria) this;
		}

		public Criteria andDoctorIdLessThan(String value) {
			addCriterion("doctor_id <", value, "doctorId");
			return (Criteria) this;
		}

		public Criteria andDoctorIdLessThanOrEqualTo(String value) {
			addCriterion("doctor_id <=", value, "doctorId");
			return (Criteria) this;
		}

		public Criteria andDoctorIdLike(String value) {
			addCriterion("doctor_id like", value, "doctorId");
			return (Criteria) this;
		}

		public Criteria andDoctorIdNotLike(String value) {
			addCriterion("doctor_id not like", value, "doctorId");
			return (Criteria) this;
		}

		public Criteria andDoctorIdIn(List<String> values) {
			addCriterion("doctor_id in", values, "doctorId");
			return (Criteria) this;
		}

		public Criteria andDoctorIdNotIn(List<String> values) {
			addCriterion("doctor_id not in", values, "doctorId");
			return (Criteria) this;
		}

		public Criteria andDoctorIdBetween(String value1, String value2) {
			addCriterion("doctor_id between", value1, value2, "doctorId");
			return (Criteria) this;
		}

		public Criteria andDoctorIdNotBetween(String value1, String value2) {
			addCriterion("doctor_id not between", value1, value2, "doctorId");
			return (Criteria) this;
		}

		public Criteria andSignTypeIsNull() {
			addCriterion("sign_type is null");
			return (Criteria) this;
		}

		public Criteria andSignTypeIsNotNull() {
			addCriterion("sign_type is not null");
			return (Criteria) this;
		}

		public Criteria andSignTypeEqualTo(Integer value) {
			addCriterion("sign_type =", value, "signType");
			return (Criteria) this;
		}

		public Criteria andSignTypeNotEqualTo(Integer value) {
			addCriterion("sign_type <>", value, "signType");
			return (Criteria) this;
		}

		public Criteria andSignTypeGreaterThan(Integer value) {
			addCriterion("sign_type >", value, "signType");
			return (Criteria) this;
		}

		public Criteria andSignTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("sign_type >=", value, "signType");
			return (Criteria) this;
		}

		public Criteria andSignTypeLessThan(Integer value) {
			addCriterion("sign_type <", value, "signType");
			return (Criteria) this;
		}

		public Criteria andSignTypeLessThanOrEqualTo(Integer value) {
			addCriterion("sign_type <=", value, "signType");
			return (Criteria) this;
		}

		public Criteria andSignTypeIn(List<Integer> values) {
			addCriterion("sign_type in", values, "signType");
			return (Criteria) this;
		}

		public Criteria andSignTypeNotIn(List<Integer> values) {
			addCriterion("sign_type not in", values, "signType");
			return (Criteria) this;
		}

		public Criteria andSignTypeBetween(Integer value1, Integer value2) {
			addCriterion("sign_type between", value1, value2, "signType");
			return (Criteria) this;
		}

		public Criteria andSignTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("sign_type not between", value1, value2, "signType");
			return (Criteria) this;
		}

		public Criteria andSignTimeIsNull() {
			addCriterion("sign_time is null");
			return (Criteria) this;
		}

		public Criteria andSignTimeIsNotNull() {
			addCriterion("sign_time is not null");
			return (Criteria) this;
		}

		public Criteria andSignTimeEqualTo(Date value) {
			addCriterion("sign_time =", value, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeNotEqualTo(Date value) {
			addCriterion("sign_time <>", value, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeGreaterThan(Date value) {
			addCriterion("sign_time >", value, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("sign_time >=", value, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeLessThan(Date value) {
			addCriterion("sign_time <", value, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeLessThanOrEqualTo(Date value) {
			addCriterion("sign_time <=", value, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeIn(List<Date> values) {
			addCriterion("sign_time in", values, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeNotIn(List<Date> values) {
			addCriterion("sign_time not in", values, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeBetween(Date value1, Date value2) {
			addCriterion("sign_time between", value1, value2, "signTime");
			return (Criteria) this;
		}

		public Criteria andSignTimeNotBetween(Date value1, Date value2) {
			addCriterion("sign_time not between", value1, value2, "signTime");
			return (Criteria) this;
		}

		public Criteria andOutTimeIsNull() {
			addCriterion("out_time is null");
			return (Criteria) this;
		}

		public Criteria andOutTimeIsNotNull() {
			addCriterion("out_time is not null");
			return (Criteria) this;
		}

		public Criteria andOutTimeEqualTo(Date value) {
			addCriterion("out_time =", value, "outTime");
			return (Criteria) this;
		}

		public Criteria andOutTimeNotEqualTo(Date value) {
			addCriterion("out_time <>", value, "outTime");
			return (Criteria) this;
		}

		public Criteria andOutTimeGreaterThan(Date value) {
			addCriterion("out_time >", value, "outTime");
			return (Criteria) this;
		}

		public Criteria andOutTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("out_time >=", value, "outTime");
			return (Criteria) this;
		}

		public Criteria andOutTimeLessThan(Date value) {
			addCriterion("out_time <", value, "outTime");
			return (Criteria) this;
		}

		public Criteria andOutTimeLessThanOrEqualTo(Date value) {
			addCriterion("out_time <=", value, "outTime");
			return (Criteria) this;
		}

		public Criteria andOutTimeIn(List<Date> values) {
			addCriterion("out_time in", values, "outTime");
			return (Criteria) this;
		}

		public Criteria andOutTimeNotIn(List<Date> values) {
			addCriterion("out_time not in", values, "outTime");
			return (Criteria) this;
		}

		public Criteria andOutTimeBetween(Date value1, Date value2) {
			addCriterion("out_time between", value1, value2, "outTime");
			return (Criteria) this;
		}

		public Criteria andOutTimeNotBetween(Date value1, Date value2) {
			addCriterion("out_time not between", value1, value2, "outTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andInUseIsNull() {
			addCriterion("in_use is null");
			return (Criteria) this;
		}

		public Criteria andInUseIsNotNull() {
			addCriterion("in_use is not null");
			return (Criteria) this;
		}

		public Criteria andInUseEqualTo(Integer value) {
			addCriterion("in_use =", value, "inUse");
			return (Criteria) this;
		}

		public Criteria andInUseNotEqualTo(Integer value) {
			addCriterion("in_use <>", value, "inUse");
			return (Criteria) this;
		}

		public Criteria andInUseGreaterThan(Integer value) {
			addCriterion("in_use >", value, "inUse");
			return (Criteria) this;
		}

		public Criteria andInUseGreaterThanOrEqualTo(Integer value) {
			addCriterion("in_use >=", value, "inUse");
			return (Criteria) this;
		}

		public Criteria andInUseLessThan(Integer value) {
			addCriterion("in_use <", value, "inUse");
			return (Criteria) this;
		}

		public Criteria andInUseLessThanOrEqualTo(Integer value) {
			addCriterion("in_use <=", value, "inUse");
			return (Criteria) this;
		}

		public Criteria andInUseIn(List<Integer> values) {
			addCriterion("in_use in", values, "inUse");
			return (Criteria) this;
		}

		public Criteria andInUseNotIn(List<Integer> values) {
			addCriterion("in_use not in", values, "inUse");
			return (Criteria) this;
		}

		public Criteria andInUseBetween(Integer value1, Integer value2) {
			addCriterion("in_use between", value1, value2, "inUse");
			return (Criteria) this;
		}

		public Criteria andInUseNotBetween(Integer value1, Integer value2) {
			addCriterion("in_use not between", value1, value2, "inUse");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table jy_org_doc_rel
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jy_org_doc_rel
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}