package com.semioe.api.entity;

import java.io.Serializable;
import java.util.Date;

public class PersonalTailor implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 844733417044464744L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_tailor.id
	 *
	 * @mbg.generated
	 */

	private String richText;

	public String getRichText() {
		return richText;
	}

	public void setRichText(String richText) {
		this.richText = richText;
	}

	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_tailor.apply_type
	 *
	 * @mbg.generated
	 */
	private Integer implementId;

	public Integer getImplementId() {
		return implementId;
	}

	public void setImplementId(Integer implementId) {
		this.implementId = implementId;
	}

	private Integer applyType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_tailor.img_url
	 *
	 * @mbg.generated
	 */
	private String imgUrl;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_tailor.title
	 *
	 * @mbg.generated
	 */
	private String title;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_tailor.description
	 *
	 * @mbg.generated
	 */
	private String description;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_tailor.display_order
	 *
	 * @mbg.generated
	 */
	private Integer displayOrder;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_tailor.create_time
	 *
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_tailor.update_time
	 *
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column personal_tailor.in_use
	 *
	 * @mbg.generated
	 */
	private Integer inUse;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column personal_tailor.id
	 *
	 * @return the value of personal_tailor.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column personal_tailor.id
	 *
	 * @param id
	 *            the value for personal_tailor.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column personal_tailor.apply_type
	 *
	 * @return the value of personal_tailor.apply_type
	 *
	 * @mbg.generated
	 */
	public Integer getApplyType() {
		return applyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column personal_tailor.apply_type
	 *
	 * @param applyType
	 *            the value for personal_tailor.apply_type
	 *
	 * @mbg.generated
	 */
	public void setApplyType(Integer applyType) {
		this.applyType = applyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column personal_tailor.img_url
	 *
	 * @return the value of personal_tailor.img_url
	 *
	 * @mbg.generated
	 */
	public String getImgUrl() {
		return imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column personal_tailor.img_url
	 *
	 * @param imgUrl
	 *            the value for personal_tailor.img_url
	 *
	 * @mbg.generated
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl == null ? null : imgUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column personal_tailor.title
	 *
	 * @return the value of personal_tailor.title
	 *
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column personal_tailor.title
	 *
	 * @param title
	 *            the value for personal_tailor.title
	 *
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column personal_tailor.description
	 *
	 * @return the value of personal_tailor.description
	 *
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column personal_tailor.description
	 *
	 * @param description
	 *            the value for personal_tailor.description
	 *
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column personal_tailor.display_order
	 *
	 * @return the value of personal_tailor.display_order
	 *
	 * @mbg.generated
	 */
	public Integer getDisplayOrder() {
		return displayOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column personal_tailor.display_order
	 *
	 * @param displayOrder
	 *            the value for personal_tailor.display_order
	 *
	 * @mbg.generated
	 */
	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column personal_tailor.create_time
	 *
	 * @return the value of personal_tailor.create_time
	 *
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column personal_tailor.create_time
	 *
	 * @param createTime
	 *            the value for personal_tailor.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column personal_tailor.update_time
	 *
	 * @return the value of personal_tailor.update_time
	 *
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column personal_tailor.update_time
	 *
	 * @param updateTime
	 *            the value for personal_tailor.update_time
	 *
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column personal_tailor.in_use
	 *
	 * @return the value of personal_tailor.in_use
	 *
	 * @mbg.generated
	 */
	public Integer getInUse() {
		return inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column personal_tailor.in_use
	 *
	 * @param inUse
	 *            the value for personal_tailor.in_use
	 *
	 * @mbg.generated
	 */
	public void setInUse(Integer inUse) {
		this.inUse = inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PersonalTailor other = (PersonalTailor) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getApplyType() == null ? other.getApplyType() == null
						: this.getApplyType().equals(other.getApplyType()))
				&& (this.getImgUrl() == null ? other.getImgUrl() == null
						: this.getImgUrl().equals(other.getImgUrl()))
				&& (this.getTitle() == null ? other.getTitle() == null
						: this.getTitle().equals(other.getTitle()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()))
				&& (this.getDisplayOrder() == null ? other.getDisplayOrder() == null
						: this.getDisplayOrder().equals(other.getDisplayOrder()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getInUse() == null ? other.getInUse() == null
						: this.getInUse().equals(other.getInUse()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getApplyType() == null) ? 0 : getApplyType().hashCode());
		result = prime * result + ((getImgUrl() == null) ? 0 : getImgUrl().hashCode());
		result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
		result = prime * result + ((getDisplayOrder() == null) ? 0 : getDisplayOrder().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getInUse() == null) ? 0 : getInUse().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", applyType=").append(applyType);
		sb.append(", imgUrl=").append(imgUrl);
		sb.append(", title=").append(title);
		sb.append(", description=").append(description);
		sb.append(", displayOrder=").append(displayOrder);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", inUse=").append(inUse);
		sb.append("]");
		return sb.toString();
	}
}