package com.semioe.api.entity;

import java.io.Serializable;
import java.util.Date;

public class UserShareService implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -9065657749057067051L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_share_service.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_share_service.service_name
	 *
	 * @mbg.generated
	 */
	private String serviceName;
	
	private int serviceId;
	
	

	public int getServiceId() {
		return serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_share_service.description
	 *
	 * @mbg.generated
	 */
	private String description;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_share_service.share_name
	 *
	 * @mbg.generated
	 */
	private String shareName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_share_service.share_id
	 *
	 * @mbg.generated
	 */
	private String shareId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_share_service.org_id
	 *
	 * @mbg.generated
	 */
	private String orgId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_share_service.create_time
	 *
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_share_service.update_time
	 *
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_share_service.in_use
	 *
	 * @mbg.generated
	 */
	private Integer inUse;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_share_service.id
	 *
	 * @return the value of user_share_service.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_share_service.id
	 *
	 * @param id
	 *            the value for user_share_service.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_share_service.service_name
	 *
	 * @return the value of user_share_service.service_name
	 *
	 * @mbg.generated
	 */
	public String getServiceName() {
		return serviceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_share_service.service_name
	 *
	 * @param serviceName
	 *            the value for user_share_service.service_name
	 *
	 * @mbg.generated
	 */
	public void setServiceName(String serviceName) {
		this.serviceName = serviceName == null ? null : serviceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_share_service.description
	 *
	 * @return the value of user_share_service.description
	 *
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_share_service.description
	 *
	 * @param description
	 *            the value for user_share_service.description
	 *
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_share_service.share_name
	 *
	 * @return the value of user_share_service.share_name
	 *
	 * @mbg.generated
	 */
	public String getShareName() {
		return shareName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_share_service.share_name
	 *
	 * @param shareName
	 *            the value for user_share_service.share_name
	 *
	 * @mbg.generated
	 */
	public void setShareName(String shareName) {
		this.shareName = shareName == null ? null : shareName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_share_service.share_id
	 *
	 * @return the value of user_share_service.share_id
	 *
	 * @mbg.generated
	 */
	public String getShareId() {
		return shareId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_share_service.share_id
	 *
	 * @param shareId
	 *            the value for user_share_service.share_id
	 *
	 * @mbg.generated
	 */
	public void setShareId(String shareId) {
		this.shareId = shareId == null ? null : shareId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_share_service.org_id
	 *
	 * @return the value of user_share_service.org_id
	 *
	 * @mbg.generated
	 */
	public String getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_share_service.org_id
	 *
	 * @param orgId
	 *            the value for user_share_service.org_id
	 *
	 * @mbg.generated
	 */
	public void setOrgId(String orgId) {
		this.orgId = orgId == null ? null : orgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_share_service.create_time
	 *
	 * @return the value of user_share_service.create_time
	 *
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_share_service.create_time
	 *
	 * @param createTime
	 *            the value for user_share_service.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_share_service.update_time
	 *
	 * @return the value of user_share_service.update_time
	 *
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_share_service.update_time
	 *
	 * @param updateTime
	 *            the value for user_share_service.update_time
	 *
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_share_service.in_use
	 *
	 * @return the value of user_share_service.in_use
	 *
	 * @mbg.generated
	 */
	public Integer getInUse() {
		return inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_share_service.in_use
	 *
	 * @param inUse
	 *            the value for user_share_service.in_use
	 *
	 * @mbg.generated
	 */
	public void setInUse(Integer inUse) {
		this.inUse = inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_share_service
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UserShareService other = (UserShareService) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getServiceName() == null ? other.getServiceName() == null
						: this.getServiceName().equals(other.getServiceName()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()))
				&& (this.getShareName() == null ? other.getShareName() == null
						: this.getShareName().equals(other.getShareName()))
				&& (this.getShareId() == null ? other.getShareId() == null
						: this.getShareId().equals(other.getShareId()))
				&& (this.getOrgId() == null ? other.getOrgId() == null
						: this.getOrgId().equals(other.getOrgId()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getInUse() == null ? other.getInUse() == null
						: this.getInUse().equals(other.getInUse()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_share_service
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getServiceName() == null) ? 0 : getServiceName().hashCode());
		result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
		result = prime * result + ((getShareName() == null) ? 0 : getShareName().hashCode());
		result = prime * result + ((getShareId() == null) ? 0 : getShareId().hashCode());
		result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getInUse() == null) ? 0 : getInUse().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_share_service
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", serviceName=").append(serviceName);
		sb.append(", description=").append(description);
		sb.append(", shareName=").append(shareName);
		sb.append(", shareId=").append(shareId);
		sb.append(", orgId=").append(orgId);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", inUse=").append(inUse);
		sb.append("]");
		return sb.toString();
	}
}