package com.semioe.api.vo;

import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.semioe.api.entity.DepartmentDic;
import com.semioe.common.pageUtil.PageInfo;

public class BackstageUserInfoVO extends PageInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.manager_id
	 * 
	 * @mbg.generated
	 */
	private int id;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	private String managerId;

	private String designOrgId;

	private String designOrgName;

	public String getDesignOrgName() {
		return designOrgName;
	}

	public void setDesignOrgName(String designOrgName) {
		this.designOrgName = designOrgName;
	}

	public String getDesignOrgId() {
		return designOrgId;
	}

	public void setDesignOrgId(String designOrgId) {
		this.designOrgId = designOrgId;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.name
	 * 
	 * @mbg.generated
	 */
	private String name;

	private String deptId;
	private String deptName;
	private String deptIds;
	private String tagIds;
	private String deptNames;
	private String tagNames;
	private Integer buildType; // 1 家医 3：孕产

	public Integer getBuildType() {
		return buildType;
	}

	public void setBuildType(Integer buildType) {
		this.buildType = buildType;
	}

	public String getTagIds() {
		return tagIds;
	}

	public void setTagIds(String tagIds) {
		this.tagIds = tagIds;
	}

	public String getTagNames() {
		return tagNames;
	}

	public void setTagNames(String tagNames) {
		this.tagNames = tagNames;
	}

	public String getDeptIds() {
		return deptIds;
	}

	public void setDeptIds(String deptIds) {
		this.deptIds = deptIds;
	}

	public String getDeptNames() {
		return deptNames;
	}

	public void setDeptNames(String deptNames) {
		this.deptNames = deptNames;
	}

	private String roleName;

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	private List<DepartmentDic> listDepart;

	public List<DepartmentDic> getListDepart() {
		return listDepart;
	}

	public void setListDepart(List<DepartmentDic> listDepart) {
		this.listDepart = listDepart;
	}

	public String getDeptId() {
		return deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	private String provinceCode;

	private String cityCode;

	private String townCode;

	public String getProvinceCode() {
		return provinceCode;
	}

	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}

	public String getCityCode() {
		return cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	public String getTownCode() {
		return townCode;
	}

	public void setTownCode(String townCode) {
		this.townCode = townCode;
	}

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	private Date expirationDate;
	private List<Integer> listRole;

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "PRC")
	public Date getExpirationDate() {
		return expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public List<Integer> getListRole() {
		return listRole;
	}

	public void setListRole(List<Integer> listRole) {
		this.listRole = listRole;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.image_url
	 * 
	 * @mbg.generated
	 */
	private String imageUrl;

	private String desc;

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.type
	 * 
	 * @mbg.generated
	 */
	private String type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.address
	 * 
	 * @mbg.generated
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.company
	 * 
	 * @mbg.generated
	 */
	private String company;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.skills
	 * 
	 * @mbg.generated
	 */
	private String skills;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.title
	 * 
	 * @mbg.generated
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.certifications_url
	 * 
	 * @mbg.generated
	 */
	private String certificationsUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.role_id
	 * 
	 * @mbg.generated
	 */
	private Integer roleId;

	private String roles;

	public String getRoles() {
		return roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.user_status
	 * 
	 * @mbg.generated
	 */
	private Integer userStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.email
	 * 
	 * @mbg.generated
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.mobile
	 * 
	 * @mbg.generated
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.create_time
	 * 
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.update_time
	 * 
	 * @mbg.generated
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column backstage_user_info.in_use
	 * 
	 * @mbg.generated
	 */
	private Integer inUse;

	/**
	 * 医生签约状态：0，待通过；1，已加入；2，已拒绝； 3，已过期
	 */
	private Integer doctorSignType;
	/**
	 * 医生签约结束时间
	 */
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	private Date doctorOutTime;

	public Integer getDoctorSignType() {
		return doctorSignType;
	}

	public void setDoctorSignType(Integer doctorSignType) {
		this.doctorSignType = doctorSignType;
	}

	public Date getDoctorOutTime() {
		return doctorOutTime;
	}

	public void setDoctorOutTime(Date doctorOutTime) {
		this.doctorOutTime = doctorOutTime;
	}

	public String getManagerId() {
		return managerId;
	}

	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getSkills() {
		return skills;
	}

	public void setSkills(String skills) {
		this.skills = skills;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCertificationsUrl() {
		return certificationsUrl;
	}

	public void setCertificationsUrl(String certificationsUrl) {
		this.certificationsUrl = certificationsUrl;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getUserStatus() {
		return userStatus;
	}

	public void setUserStatus(Integer userStatus) {
		this.userStatus = userStatus;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getInUse() {
		return inUse;
	}

	public void setInUse(Integer inUse) {
		this.inUse = inUse;
	}

	private Integer skip;

	private Integer limit;

	public Integer getSkip() {
		return super.getCurrentResult();
	}

	private Integer getLimit() {
		return super.getCurrentResult() + super.getShowCount();
	}
}
