package com.semioe.api.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.semioe.api.entity.GoodsInfo;
import com.semioe.api.entity.Keywords;
import com.semioe.common.pageUtil.PageInfo;
import java.util.Date;
import java.util.List;

public class ServiceInfoVO extends PageInfo {

	private Integer id;

	private String name;

	private Double price;

	private String procedureId;

	private String procedureName;

	private Integer status;

	private String opinion;

	private String createUserId;

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	private Date createTime;

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "PRC")
	private Date updateTime;

	private Integer inUse;

	private String description;

	private String goodsIdList;

	private String keywordsIdList;

	private String keywordsName;

	private List<Keywords> keywordsList;

	private List<GoodsInfo> goodsInfoList;

	private List<Integer> statusList;

	private List<String> keywordsNameList;
	
	private List<Integer> idList;

	// 20170922 创建类型 ：1：其他 2：运营
	private int buildType;

	// 20171031
	private int serviceAttribute; // 服务属性 1：公开购买 2：个人推荐
	private int serviceType; // 服务类型 1：体重 2：外科 等等。。。详见码表
	private int serviceShare; // 服务共享 0：初始状态 1：共享 2：取消共享
	private String imgUrl; // 图片
	private int fromType; // 调用方类型 1：前端 2：后台

	public List<Integer> getIdList() {
		return idList;
	}
	public void setIdList(List<Integer> idList) {
		this.idList = idList;
	}

	public int getFromType() {
		return fromType;
	}

	public void setFromType(int fromType) {
		this.fromType = fromType;
	}

	public int getServiceAttribute() {
		return serviceAttribute;
	}

	public void setServiceAttribute(int serviceAttribute) {
		this.serviceAttribute = serviceAttribute;
	}

	public int getServiceType() {
		return serviceType;
	}

	public void setServiceType(int serviceType) {
		this.serviceType = serviceType;
	}

	public int getServiceShare() {
		return serviceShare;
	}

	public void setServiceShare(int serviceShare) {
		this.serviceShare = serviceShare;
	}

	public String getImgUrl() {
		return imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public int getBuildType() {
		return buildType;
	}

	public void setBuildType(int buildType) {
		this.buildType = buildType;
	}

	public List<String> getKeywordsNameList() {
		return keywordsNameList;
	}

	public void setKeywordsNameList(List<String> keywordsNameList) {
		this.keywordsNameList = keywordsNameList;
	}

	public String getProcedureName() {
		return procedureName;
	}

	public void setProcedureName(String procedureName) {
		this.procedureName = procedureName;
	}

	public List<Integer> getStatusList() {
		return statusList;
	}

	public void setStatusList(List<Integer> statusList) {
		this.statusList = statusList;
	}

	public List<Keywords> getKeywordsList() {
		return keywordsList;
	}

	public void setKeywordsList(List<Keywords> keywordsList) {
		this.keywordsList = keywordsList;
	}

	public List<GoodsInfo> getGoodsInfoList() {
		return goodsInfoList;
	}

	public void setGoodsInfoList(List<GoodsInfo> goodsInfoList) {
		this.goodsInfoList = goodsInfoList;
	}

	private String createName;

	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	public String getKeywordsIdList() {
		return keywordsIdList;
	}

	public void setKeywordsIdList(String keywordsIdList) {
		this.keywordsIdList = keywordsIdList;
	}

	public String getKeywordsName() {
		return keywordsName;
	}

	public void setKeywordsName(String keywordsName) {
		this.keywordsName = keywordsName;
	}

	public String getGoodsIdList() {
		return goodsIdList;
	}

	public void setGoodsIdList(String goodsIdList) {
		this.goodsIdList = goodsIdList;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getProcedureId() {
		return procedureId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column service_info.procedure_id
	 *
	 * @param procedureId
	 *            the value for service_info.procedure_id
	 *
	 * @mbg.generated
	 */
	public void setProcedureId(String procedureId) {
		this.procedureId = procedureId == null ? null : procedureId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column service_info.status
	 *
	 * @return the value of service_info.status
	 *
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column service_info.status
	 *
	 * @param status
	 *            the value for service_info.status
	 *
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column service_info.opinion
	 *
	 * @return the value of service_info.opinion
	 *
	 * @mbg.generated
	 */
	public String getOpinion() {
		return opinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column service_info.opinion
	 *
	 * @param opinion
	 *            the value for service_info.opinion
	 *
	 * @mbg.generated
	 */
	public void setOpinion(String opinion) {
		this.opinion = opinion == null ? null : opinion.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column service_info.create_user_id
	 *
	 * @return the value of service_info.create_user_id
	 *
	 * @mbg.generated
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column service_info.create_user_id
	 *
	 * @param createUserId
	 *            the value for service_info.create_user_id
	 *
	 * @mbg.generated
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column service_info.create_time
	 *
	 * @return the value of service_info.create_time
	 *
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column service_info.create_time
	 *
	 * @param createTime
	 *            the value for service_info.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column service_info.update_time
	 *
	 * @return the value of service_info.update_time
	 *
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column service_info.update_time
	 *
	 * @param updateTime
	 *            the value for service_info.update_time
	 *
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column service_info.in_use
	 *
	 * @return the value of service_info.in_use
	 *
	 * @mbg.generated
	 */
	public Integer getInUse() {
		return inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column service_info.in_use
	 *
	 * @param inUse
	 *            the value for service_info.in_use
	 *
	 * @mbg.generated
	 */
	public void setInUse(Integer inUse) {
		this.inUse = inUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column service_info.describe
	 *
	 * @return the value of service_info.describe
	 *
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column service_info.describe
	 *
	 * @param describe
	 *            the value for service_info.describe
	 *
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ServiceInfoVO other = (ServiceInfoVO) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null
						: this.getName().equals(other.getName()))
				&& (this.getPrice() == null ? other.getPrice() == null
						: this.getPrice().equals(other.getPrice()))
				&& (this.getProcedureId() == null ? other.getProcedureId() == null
						: this.getProcedureId().equals(other.getProcedureId()))
				&& (this.getStatus() == null ? other.getStatus() == null
						: this.getStatus().equals(other.getStatus()))
				&& (this.getOpinion() == null ? other.getOpinion() == null
						: this.getOpinion().equals(other.getOpinion()))
				&& (this.getCreateUserId() == null ? other.getCreateUserId() == null
						: this.getCreateUserId().equals(other.getCreateUserId()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getInUse() == null ? other.getInUse() == null
						: this.getInUse().equals(other.getInUse()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
		result = prime * result + ((getProcedureId() == null) ? 0 : getProcedureId().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getOpinion() == null) ? 0 : getOpinion().hashCode());
		result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result + ((getInUse() == null) ? 0 : getInUse().hashCode());
		result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", name=").append(name);
		sb.append(", price=").append(price);
		sb.append(", procedureId=").append(procedureId);
		sb.append(", status=").append(status);
		sb.append(", opinion=").append(opinion);
		sb.append(", createUserId=").append(createUserId);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", inUse=").append(inUse);
		sb.append(", description=").append(description);
		sb.append("]");
		return sb.toString();
	}
}