package com.semioe.dubbo.dao;

import com.semioe.api.entity.AddressProvince;
import com.semioe.api.entity.AddressProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddressProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address_province
     *
     * @mbg.generated
     */
    long countByExample(AddressProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address_province
     *
     * @mbg.generated
     */
    int deleteByExample(AddressProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address_province
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address_province
     *
     * @mbg.generated
     */
    int insert(AddressProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address_province
     *
     * @mbg.generated
     */
    int insertSelective(AddressProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address_province
     *
     * @mbg.generated
     */
    List<AddressProvince> selectByExample(AddressProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address_province
     *
     * @mbg.generated
     */
    AddressProvince selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address_province
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AddressProvince record, @Param("example") AddressProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address_province
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AddressProvince record, @Param("example") AddressProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AddressProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AddressProvince record);
}