package com.semioe.dubbo.dao;

import com.semioe.api.entity.ApiContractedUser;
import com.semioe.api.entity.ApiContractedUserExample;
import com.semioe.api.vo.ApiContractedUserVO;
import com.semioe.api.vo.ApiUserInfoVO;
import com.semioe.api.vo.UserCountVO;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApiContractedUserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_contracted_user
	 *
	 * @mbg.generated
	 */
	long countByExample(ApiContractedUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_contracted_user
	 *
	 * @mbg.generated
	 */
	int deleteByExample(ApiContractedUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_contracted_user
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_contracted_user
	 *
	 * @mbg.generated
	 */
	int insert(ApiContractedUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_contracted_user
	 *
	 * @mbg.generated
	 */
	int insertSelective(ApiContractedUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_contracted_user
	 *
	 * @mbg.generated
	 */
	List<ApiContractedUser> selectByExample(ApiContractedUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_contracted_user
	 *
	 * @mbg.generated
	 */
	ApiContractedUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_contracted_user
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") ApiContractedUser record,
			@Param("example") ApiContractedUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_contracted_user
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") ApiContractedUser record,
			@Param("example") ApiContractedUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_contracted_user
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ApiContractedUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table api_contracted_user
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ApiContractedUser record);

	ApiContractedUserVO selectInfoByPrimaryKey(Integer id);

	ApiContractedUserVO selectByObject(ApiContractedUser record);

	ApiUserInfoVO selectApiUserByEntity(ApiContractedUserVO record);

	int insertUserVO(ApiContractedUserVO apiUserInfo);

	List<UserCountVO> selectAllBySex(ApiUserInfoVO userInfo);

	List<UserCountVO> selectAllBySexSummary(ApiUserInfoVO userInfo);

	List<UserCountVO> selectAllByAge(ApiUserInfoVO userInfo);

	List<UserCountVO> selectAllByAgeSummary(ApiUserInfoVO userInfo);

	List<UserCountVO> selectAllBySignOrg(ApiUserInfoVO userInfo);

	List<UserCountVO> selectAllBySignOrgSummary(ApiUserInfoVO userInfo);

	List<UserCountVO> selectAllBySignDoc(ApiUserInfoVO userInfo);

	List<UserCountVO> selectAllBySignDocSummary(ApiUserInfoVO userInfo);

	List<UserCountVO> selectAllByDisease(ApiUserInfoVO userInfo);

	List<UserCountVO> selectAllByDiseaseSummary(ApiUserInfoVO userInfo);

	List<UserCountVO> selectFamilySummaryCountListPage(ApiUserInfoVO userInfo);
	
	List<UserCountVO> selectFamilyCountListPage(ApiUserInfoVO userInfo);

	List<UserCountVO> selectAllByFamilySummary(ApiUserInfoVO userInfo);

	List<ApiContractedUserVO> selectAllByFamilyDetailListPage(UserCountVO userInfo);

	List<ApiContractedUserVO> getAllUserByConditionListPage(ApiContractedUserVO apiUserInfo);

}