package com.semioe.dubbo.dao;

import com.semioe.api.entity.Keywords;
import com.semioe.api.entity.KeywordsRel;
import com.semioe.api.entity.KeywordsRelExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface KeywordsRelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table keywords_rel
	 * 
	 * @mbg.generated
	 */
	long countByExample(KeywordsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table keywords_rel
	 * 
	 * @mbg.generated
	 */
	int deleteByExample(KeywordsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table keywords_rel
	 * 
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table keywords_rel
	 * 
	 * @mbg.generated
	 */
	int insert(KeywordsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table keywords_rel
	 * 
	 * @mbg.generated
	 */
	int insertSelective(KeywordsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table keywords_rel
	 * 
	 * @mbg.generated
	 */
	List<KeywordsRel> selectByExample(KeywordsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table keywords_rel
	 * 
	 * @mbg.generated
	 */
	KeywordsRel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table keywords_rel
	 * 
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") KeywordsRel record,
			@Param("example") KeywordsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table keywords_rel
	 * 
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") KeywordsRel record,
			@Param("example") KeywordsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table keywords_rel
	 * 
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(KeywordsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table keywords_rel
	 * 
	 * @mbg.generated
	 */
	int updateByPrimaryKey(KeywordsRel record);

	List<KeywordsRel> selectByKeywords(String[] keywords);

	/** 批量新增关系数据 */
	int insertList(List<KeywordsRel> KeywordsRelList);

	/** 根据关系id 删除关系数据 */
	int deleteByRelationId(Integer relationId , Integer type);

	/** 根据id 查询关系数据名称 */
	List<Map<String, Object>> selectByRelationId(Integer relationId , Integer type);

	List<Keywords> selectListByRelationId(Integer relationId , Integer type);

}