package com.semioe.dubbo.dao;

import com.semioe.api.entity.MeasuringItemsRule;
import com.semioe.api.entity.MeasuringItemsRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MeasuringItemsRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measuring_items_rule
     *
     * @mbg.generated
     */
    long countByExample(MeasuringItemsRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measuring_items_rule
     *
     * @mbg.generated
     */
    int deleteByExample(MeasuringItemsRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measuring_items_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measuring_items_rule
     *
     * @mbg.generated
     */
    int insert(MeasuringItemsRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measuring_items_rule
     *
     * @mbg.generated
     */
    int insertSelective(MeasuringItemsRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measuring_items_rule
     *
     * @mbg.generated
     */
    List<MeasuringItemsRule> selectByExample(MeasuringItemsRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measuring_items_rule
     *
     * @mbg.generated
     */
    MeasuringItemsRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measuring_items_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MeasuringItemsRule record, @Param("example") MeasuringItemsRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measuring_items_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MeasuringItemsRule record, @Param("example") MeasuringItemsRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measuring_items_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MeasuringItemsRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measuring_items_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MeasuringItemsRule record);
    
    List<MeasuringItemsRule> getMeasuringItemsRuleByType(String type);
}