package com.semioe.dubbo.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.semioe.api.entity.Message;
import com.semioe.api.entity.MessageExample;

public interface MessageMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	long countByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int deleteByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int insertSelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	List<Message> selectByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	Message selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") Message record,
			@Param("example") MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") Message record, @Param("example") MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Message record);

	List<Message> selectMessageListPage(Message message);
	
	/* 根据条件批量修改消息状态 */
	int updateStatusByEntity(Message message);
	
	/* 用户消息数量统计 */
	List<Message> countMessageStatusListPage(Message message);
	
	/* 统计用户消息数 */
	Message countUserMessageStatus(Message message);
	
}