package com.semioe.dubbo.dao;

import com.semioe.api.entity.OrderInfo;
import com.semioe.api.entity.OrderInfoExample;
import com.semioe.api.vo.OrderCountVO;
import com.semioe.api.vo.OrderInfoVO;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface OrderInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	long countByExample(OrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	int deleteByExample(OrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	int insert(OrderInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	int insertSelective(OrderInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	List<OrderInfo> selectByExampleWithBLOBs(OrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	List<OrderInfo> selectByExample(OrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	OrderInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") OrderInfo record, @Param("example") OrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	int updateByExampleWithBLOBs(@Param("record") OrderInfo record, @Param("example") OrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") OrderInfo record, @Param("example") OrderInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(OrderInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(OrderInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(OrderInfo record);

	/* 根据订单编号查询数据 */
	OrderInfo selectByOrderCode(String orderCode);

	/* 根据查询条件查询 总数 */
	long countByEntity(OrderInfo example);
	
	/* 根据查询条件查询 VO对象 */
	List<OrderInfoVO> selectVoByEntity(OrderInfo example);
	
	/* 查询订单列表及报表数量 */
	List<OrderInfoVO> selectVoReportCount(OrderInfo example);
	
	/* 根据ID查询 VO对象 */
	OrderInfoVO selectVoByPrimaryKey(Integer id);
	
	/* 根据订单编号查询 VO对象 */
	OrderInfoVO selectVoByOrderCode(String orderCode);
	
	/* 销售金额统计 */
    Double countTotalPriceByDate(OrderInfo example);

    /* 销售金额 按日期统计 */
    List<OrderCountVO> countPriceByDate(OrderInfo example);

    /* 销售数量统计 */
    Double countTotalAmountByDate(OrderInfo example);

    /* 销售数量 按日期统计 */
    List<OrderCountVO> countAmountByDate(OrderInfo example);

    /* 订单数量&金额 数据统计 */
    List<OrderCountVO> countOrderInfoByEntity(OrderInfo example);

    /* 订单数量&金额 数据统计 分页总数查询 */
    long pageCountOrderInfoByEntity(OrderInfo example);

    /* 查询过期订单 */
    List<OrderInfo> selectOutTimeOrders();
    
    /**
     * 家庭医生！订单查询
     */
    List<OrderInfoVO> selectJyOrderInfo(Map<String, Object> query);
	
    /**
     * 后台查询我的服务接口
     * @param query
     * @return
     */
    List<OrderInfoVO> selectBackOrderInfo(Map<String, Object> query);
    
}