package com.semioe.dubbo.dao;

import com.semioe.api.entity.PersonalTailorMessage;
import com.semioe.api.entity.PersonalTailorMessageExample;
import com.semioe.api.vo.PersonalTailorMessageVO;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonalTailorMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_tailor_message
     *
     * @mbg.generated
     */
    long countByExample(PersonalTailorMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_tailor_message
     *
     * @mbg.generated
     */
    int deleteByExample(PersonalTailorMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_tailor_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_tailor_message
     *
     * @mbg.generated
     */
    int insert(PersonalTailorMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_tailor_message
     *
     * @mbg.generated
     */
    int insertSelective(PersonalTailorMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_tailor_message
     *
     * @mbg.generated
     */
    List<PersonalTailorMessage> selectByExample(PersonalTailorMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_tailor_message
     *
     * @mbg.generated
     */
    PersonalTailorMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_tailor_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PersonalTailorMessage record, @Param("example") PersonalTailorMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_tailor_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PersonalTailorMessage record, @Param("example") PersonalTailorMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_tailor_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PersonalTailorMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_tailor_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PersonalTailorMessage record);
    
    /**
     * 条件分页查询
     * @param personalTailorMessageVO
     * @return
     */
    List<PersonalTailorMessage> queryPTMListPage(PersonalTailorMessageVO personalTailorMessageVO);
}