package com.semioe.dubbo.dao;

import com.semioe.api.entity.PersonalTailor;
import com.semioe.api.entity.PersonalTailorExample;
import com.semioe.api.vo.PersonalTailorVO;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface PersonalTailorMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	long countByExample(PersonalTailorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	int deleteByExample(PersonalTailorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	int insert(PersonalTailor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	int insertSelective(PersonalTailor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	List<PersonalTailor> selectByExample(PersonalTailorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	PersonalTailor selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") PersonalTailor record,
			@Param("example") PersonalTailorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") PersonalTailor record,
			@Param("example") PersonalTailorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PersonalTailor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table personal_tailor
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PersonalTailor record);

	int updateInUse(Map<String, Object> updateMap);

	List<PersonalTailor> selectByEntity(PersonalTailorVO entity);

	List<PersonalTailorVO> selectEntityByConditionListPage(PersonalTailorVO entity);

	List<PersonalTailorVO> selectEntityByCondition(PersonalTailorVO entity);
}