package com.semioe.dubbo.dao;

import com.semioe.api.entity.ServiceInfo;
import com.semioe.api.entity.ServiceInfoExample;
import com.semioe.api.vo.ServiceInfoVO;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface ServiceInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	long countByExample(ServiceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	int deleteByExample(ServiceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	int insert(ServiceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	int insertSelective(ServiceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	List<ServiceInfo> selectByExampleWithBLOBs(ServiceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	List<ServiceInfo> selectByExample(ServiceInfoExample example);

	List<ServiceInfoVO> selectByConditionListPage(ServiceInfoVO serviceVO);

	// 家医 20170922
	List<Map<String, Object>> selectJyByConditionListPage(ServiceInfoVO serviceVO);

	List<Map<String, Object>> selectJyConditionList(ServiceInfoVO serviceVO);

	int insertJy(ServiceInfo record);

	List<Map<String, Object>> selectById(ServiceInfoVO serviceVO);

	int updateInUse(Map<String, Object> updateMap);

	ServiceInfoVO selectServiceAndUserById(Integer serviceId);

	List<ServiceInfo> selectServiceByName(ServiceInfoVO serviceInfoVO);

	List<ServiceInfo> selectByUserIdAndStatus(ServiceInfoVO serviceInfoVO);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	ServiceInfo selectByPrimaryKey(Integer id);

	ServiceInfoVO selectVOByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") ServiceInfo record,
			@Param("example") ServiceInfoExample example);

	int updateStatus(Map<String, Object> updateMap);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	int updateByExampleWithBLOBs(@Param("record") ServiceInfo record,
			@Param("example") ServiceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") ServiceInfo record,
			@Param("example") ServiceInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ServiceInfoVO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(ServiceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_info
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ServiceInfo record);

	/* 根据关键字 查询服务数据列表 */
	List<ServiceInfoVO> getServiceInfoVoByKeywords(ServiceInfoVO serviceVO);

	/* 根据关键字 查询服务数据列表总数量 */
	long countServiceInfoVoByKeywords(ServiceInfoVO serviceVO);

	/* 根据服务对象VO 查询服务 */
	List<ServiceInfo> selectByParameter(ServiceInfoVO serviceVO);

	// 20171031
	List<ServiceInfoVO> selectAllListPage(ServiceInfoVO serviceVO);

	List<ServiceInfoVO> selectAllList(ServiceInfoVO serviceVO);
}