package com.semioe.dubbo.dao;

import com.semioe.api.entity.GoodsInfo;
import com.semioe.api.entity.ServiceGoodsRel;
import com.semioe.api.entity.ServiceGoodsRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceGoodsRelMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_goods_rel
	 *
	 * @mbg.generated
	 */
	long countByExample(ServiceGoodsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_goods_rel
	 *
	 * @mbg.generated
	 */
	int deleteByExample(ServiceGoodsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_goods_rel
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_goods_rel
	 *
	 * @mbg.generated
	 */
	int insert(ServiceGoodsRel record);

	int insertList(List<ServiceGoodsRel> records);

	int deleteByServiceId(Integer serviceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_goods_rel
	 *
	 * @mbg.generated
	 */
	int insertSelective(ServiceGoodsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_goods_rel
	 *
	 * @mbg.generated
	 */
	List<ServiceGoodsRel> selectByExample(ServiceGoodsRelExample example);

	List<GoodsInfo> selectGoodsById(Integer serviceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_goods_rel
	 *
	 * @mbg.generated
	 */
	ServiceGoodsRel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_goods_rel
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") ServiceGoodsRel record,
			@Param("example") ServiceGoodsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_goods_rel
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") ServiceGoodsRel record,
			@Param("example") ServiceGoodsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_goods_rel
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ServiceGoodsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table service_goods_rel
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ServiceGoodsRel record);
}