package com.semioe.dubbo.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.semioe.api.entity.TagsRel;
import com.semioe.api.entity.TagsRelExample;

public interface TagsRelMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tags_rel
	 *
	 * @mbg.generated
	 */
	long countByExample(TagsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tags_rel
	 *
	 * @mbg.generated
	 */
	int deleteByExample(TagsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tags_rel
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tags_rel
	 *
	 * @mbg.generated
	 */
	int insert(TagsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tags_rel
	 *
	 * @mbg.generated
	 */
	int insertSelective(TagsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tags_rel
	 *
	 * @mbg.generated
	 */
	List<TagsRel> selectByExample(TagsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tags_rel
	 *
	 * @mbg.generated
	 */
	TagsRel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tags_rel
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TagsRel record, @Param("example") TagsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tags_rel
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TagsRel record, @Param("example") TagsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tags_rel
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TagsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tags_rel
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TagsRel record);

	int insertTagsRels(List<TagsRel> tagsRelList);
}