package com.semioe.dubbo.dao;

import com.semioe.api.entity.UserHealthyLiving;
import com.semioe.api.entity.UserHealthyLivingExample;
import com.semioe.api.vo.UserHealthyLivingVO;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserHealthyLivingMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_healthy_living
	 *
	 * @mbg.generated
	 */
	long countByExample(UserHealthyLivingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_healthy_living
	 *
	 * @mbg.generated
	 */
	int deleteByExample(UserHealthyLivingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_healthy_living
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_healthy_living
	 *
	 * @mbg.generated
	 */
	int insert(UserHealthyLiving record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_healthy_living
	 *
	 * @mbg.generated
	 */
	int insertSelective(UserHealthyLiving record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_healthy_living
	 *
	 * @mbg.generated
	 */
	List<UserHealthyLiving> selectByExample(UserHealthyLivingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_healthy_living
	 *
	 * @mbg.generated
	 */
	UserHealthyLiving selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_healthy_living
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") UserHealthyLiving record,
			@Param("example") UserHealthyLivingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_healthy_living
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") UserHealthyLiving record,
			@Param("example") UserHealthyLivingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_healthy_living
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(UserHealthyLiving record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_healthy_living
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(UserHealthyLiving record);

	List<UserHealthyLivingVO> selectByUserId(Integer userId);

	List<UserHealthyLivingVO> selectByUserIdAndTypeId(UserHealthyLivingVO uh);

	int deleteByUserId(Integer userId);

	int insertHealthyVOList(List<UserHealthyLivingVO> healthyVOList);
}